"use client";
import {useEffect,useRef,useState} from 'react';
import type {useTripSelection} from '../hooks/useTripSelection';
import type {VisitInfo} from '../../../lib/visit-hours.js';
import {budgetIdentity,cleanBudget,knownWon,readBudget,writeBudget,summarizeBudget,TRIP_BUDGET_KEY,type TripBudget as BudgetValue,type RouteCost} from '../../../lib/trip-budget.js';
import {fetchVisitInfo} from '../services/visit-info';

const fieldStyle={width:'100%',minHeight:48,padding:'10px 12px',border:'1px solid var(--line)',borderRadius:12,color:'var(--ink)',background:'var(--paper)',fontSize:16} as const;
const labelStyle={display:'grid',gap:8,fontSize:14} as const;
const gridStyle={display:'grid',gap:16,gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,180px),1fr))'} as const;
const won=(amount:number)=>amount.toLocaleString('ko-KR')+'원';
const categoryNames:Record<string,string>={food:'식사',stay:'숙박',other:'기타',admission:'입장·이용'};
type Draft={people:number;target:string;targetBasis:'person'|'group';admissions:Record<string,{amount:string;basis:'person'|'group'}>;extras:Array<{id:string;day:string;category:string;amount:string;basis:'person'|'group';label:string}>};
const draftOf=(value:BudgetValue):Draft=>({...value,target:value.target===null?'':String(value.target),admissions:Object.fromEntries(Object.entries(value.admissions).map(([id,row])=>[id,{...row,amount:String(row.amount)}])),extras:value.extras.map(row=>({...row,amount:row.amount===null?'':String(row.amount)}))});
type Props={trip:ReturnType<typeof useTripSelection>;routes:Record<string,RouteCost>;region:string};

function BudgetForm({trip,routes,region}:Props){
 const identity=budgetIdentity(trip.orderedSavedPlaces,trip.tripDays),ids=trip.orderedSavedPlaces.map(place=>place.id);
 const [saved,setSaved]=useState(()=>cleanBudget(null,ids,trip.tripDays));
 const [draft,setDraft]=useState<Draft>(()=>draftOf(saved)),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
 const [info,setInfo]=useState<Record<string,VisitInfo>>({}),[loading,setLoading]=useState('');
 const [conflict,setConflict]=useState(false);
 const initial=useRef({identity,ids,days:trip.tripDays}),lastSaved=useRef(JSON.stringify(saved));
 useEffect(()=>{
  const scope=initial.current;
  try{const value=readBudget(localStorage,scope.identity,scope.ids,scope.days,true);setSaved(value);setDraft(draftOf(value));lastSaved.current=JSON.stringify(value);}catch{setNotice('저장한 여행비를 불러오지 못했어요. 금액을 확인한 뒤 다시 저장해 주세요.');}setReady(true);
  const changed=(event:StorageEvent)=>{if(event.key!==TRIP_BUDGET_KEY&&event.key!==null)return;try{const value=readBudget(localStorage,scope.identity,scope.ids,scope.days,true);if(JSON.stringify(value)!==lastSaved.current)setConflict(true);}catch{setConflict(true);setNotice('저장된 여행비를 확인하지 못했어요. 입력한 내용은 유지됩니다.');}};window.addEventListener('storage',changed);return()=>window.removeEventListener('storage',changed);
 // A new date/place identity remounts this editor; ordinary route updates must not erase an unsaved draft.
 },[]);
 const invalid=[draft.target,...Object.values(draft.admissions).map(row=>row.amount),...draft.extras.map(row=>row.amount)].some(value=>value!==''&&knownWon(value)===null);
 const summary=summarizeBudget({places:trip.orderedSavedPlaces,days:trip.tripDays,assignments:trip.scheduleAssignments,budget:draft,routes});
 const dirty=JSON.stringify(draft)!==JSON.stringify(draftOf(saved));
 function save(){if(!ready||invalid||conflict||summary.outOfPeriod)return;try{const current=readBudget(localStorage,identity,ids,trip.tripDays,true);if(JSON.stringify(current)!==lastSaved.current){setConflict(true);return;}const next=writeBudget(localStorage,identity,draft,ids,trip.tripDays);setSaved(next);setDraft(draftOf(next));lastSaved.current=JSON.stringify(next);setNotice('여행비 계획을 저장했어요.');}catch{setNotice('여행비를 저장하지 못했어요. 입력한 내용은 유지됩니다. 화면을 떠나기 전에 여행비 요약을 파일로 챙겨두세요.');}}
 function reload(){try{const next=readBudget(localStorage,identity,ids,trip.tripDays,true);setSaved(next);setDraft(draftOf(next));lastSaved.current=JSON.stringify(next);setConflict(false);setNotice('최신 여행비 계획을 불러왔어요.');}catch{setNotice('여행비를 불러오지 못했어요. 입력한 내용은 유지됩니다.');}}
 async function checkFees(id:string){if(loading)return;setLoading(id);try{const result=await fetchVisitInfo(id);setInfo(current=>({...current,[id]:result}));setNotice('요금 안내를 확인한 뒤 적용되는 금액을 직접 입력해 주세요.');}catch{setNotice('요금 안내를 불러오지 못했어요. 확인 전까지 금액을 비워 둘 수 있습니다.');}finally{setLoading('');}}
 function exportText(){if(invalid||summary.outOfPeriod)return;const lines=[`WAVE · ${region} 여행비`,new Date().toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}),`인원 ${summary.people}명 · 확인한 금액 ${won(summary.total)} · 미확인 ${summary.unknown}항목`,summary.target===null?'전체 예산 미정':`전체 예산 ${won(summary.target)}`,...summary.rows.map(row=>`${row.day} · ${row.label||categoryNames[row.category]||row.category}: ${row.amount===null?'미확인':won(row.amount)} (${row.basis==='person'?'1인':'전체'}) · ${row.source}`),'자동차 이동비는 차량1대의 조회 통행료입니다. 연료·주차·추가 식비 등 입력하지 않은 비용은 별도입니다.'];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`WAVE-여행비-${trip.travelStart}.txt`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('현재 입력한 여행비 요약을 저장했어요.');}
 return <section className="account-settings" aria-label="여행비 계획" style={{padding:'16px clamp(12px,2vw,24px)'}}>
  <h3 style={{fontSize:22,lineHeight:1.4}}>여행비도 편하게 준비해요</h3>
  <div className="reference-info-card"><h3 style={{fontSize:24,lineHeight:1.4}}>확인한 금액 {won(summary.total)}</h3><p style={{fontSize:14}}>1인당 평균 {won(summary.perPerson)} · {summary.people}명 기준 · 미확인 {summary.unknown}항목</p><p style={{fontSize:14}}>{summary.remaining===null?'예산을 정하면 남은 금액을 함께 볼 수 있어요.':summary.remaining<0?`전체 예산보다 ${won(-summary.remaining)} 많아요.`:`전체 예산까지 ${won(summary.remaining)} 남았어요.`}</p><p style={{fontSize:13}}>미확인 금액과 아직 추가하지 않은 비용은 합계에 포함되지 않습니다. 확인한 금액을 기준으로 비교하세요.</p></div>
  <div style={gridStyle}><label style={labelStyle}>함께하는 인원<select style={fieldStyle} value={draft.people} onChange={event=>setDraft({...draft,people:Number(event.target.value)})}>{Array.from({length:30},(_,index)=><option key={index+1} value={index+1}>{index+1}명</option>)}</select></label><label style={labelStyle}>목표 예산 (원)<input style={fieldStyle} type="number" min="0" max="100000000" step="1" inputMode="numeric" value={draft.target} placeholder="아직 정하지 않았어요" onChange={event=>setDraft({...draft,target:event.target.value})}/></label><label style={labelStyle}>예산 기준<select style={fieldStyle} value={draft.targetBasis} onChange={event=>setDraft({...draft,targetBasis:event.target.value as Draft['targetBasis']})}><option value="group">여행 전체</option><option value="person">1인당</option></select></label></div>
  <details className="place-evidence"><summary>장소별 입장·이용요금</summary><div className="modal-data">{trip.orderedSavedPlaces.map(place=><article className="reference-info-card" key={place.id}><h4>{place.name}</h4><div style={gridStyle}><label style={labelStyle}>{place.name} 입장·이용요금 (원)<input style={fieldStyle} type="number" min="0" max="100000000" step="1" inputMode="numeric" value={draft.admissions[place.id]?.amount??''} placeholder="미확인" onChange={event=>setDraft({...draft,admissions:{...draft.admissions,[place.id]:{amount:event.target.value,basis:draft.admissions[place.id]?.basis||'person'}}})}/></label><label style={labelStyle}>{place.name} 요금 기준<select style={fieldStyle} value={draft.admissions[place.id]?.basis||'person'} onChange={event=>setDraft({...draft,admissions:{...draft.admissions,[place.id]:{amount:draft.admissions[place.id]?.amount||'',basis:event.target.value as Draft['targetBasis']}}})}><option value="person">1인당</option><option value="group">전체</option></select></label></div><p style={{fontSize:14}}>무료인 것이 확인되면 0원을 입력하세요.</p><div className="travel-book-actions"><button type="button" disabled={Boolean(loading)} onClick={()=>void checkFees(place.id)}>{loading===place.id?'요금 안내 확인 중…':place.name+' 공식 요금 안내'}</button></div>{info[place.id]&&<p style={{fontSize:14}}>{info[place.id].fees||'요금 안내 미확인'} · {info[place.id].source} · {new Date(info[place.id].checkedAt).toLocaleDateString('ko-KR')}</p>}</article>)}</div></details>
  <details className="place-evidence"><summary>식사·숙박과 추가 비용 {draft.extras.length}개</summary><div className="modal-data">{draft.extras.map((row,index)=>{const update=(value:Partial<typeof row>)=>setDraft({...draft,extras:draft.extras.map(item=>item.id===row.id?{...item,...value}:item)});return <fieldset key={row.id} className="reference-info-card"><legend>추가 비용 {index+1}</legend><div style={gridStyle}><label style={labelStyle}>항목 이름<input style={fieldStyle} maxLength={80} value={row.label} onChange={event=>update({label:event.target.value})}/></label><label style={labelStyle}>분류<select style={fieldStyle} value={row.category} onChange={event=>update({category:event.target.value})}>{Object.entries(categoryNames).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label style={labelStyle}>비용 날짜<select style={fieldStyle} value={row.day} onChange={event=>update({day:event.target.value})}>{trip.tripDays.map(day=><option key={day}>{day}</option>)}</select></label><label style={labelStyle}>추가 금액 (원)<input style={fieldStyle} type="number" min="0" max="100000000" step="1" inputMode="numeric" value={row.amount} placeholder="미확인" onChange={event=>update({amount:event.target.value})}/></label><label style={labelStyle}>금액 기준<select style={fieldStyle} value={row.basis} onChange={event=>update({basis:event.target.value as Draft['targetBasis']})}><option value="group">전체</option><option value="person">1인당</option></select></label></div><div className="travel-book-actions"><button type="button" onClick={()=>setDraft({...draft,extras:draft.extras.filter(item=>item.id!==row.id)})}>추가 비용 {index+1} 제거</button></div></fieldset>;})}<div className="travel-book-actions"><button type="button" disabled={draft.extras.length>=30} onClick={()=>setDraft({...draft,extras:[...draft.extras,{id:crypto.randomUUID(),day:trip.activeDay,category:'food',amount:'',basis:'group',label:''}]})}>비용 항목 추가</button></div></div></details>
  <details className="place-evidence"><summary>날짜별 합계와 조회한 이동비</summary><div className="modal-data"><ul>{summary.days.map(day=><li key={day.day}>{day.day} · {won(day.total)} · 미확인 {day.unknown}항목</li>)}</ul><ol>{summary.rows.filter(row=>row.category==='transport').map(row=><li key={row.id}>{row.label} · {row.total===null?'미확인':won(row.total)} · {row.source}</li>)}</ol><p style={{fontSize:14}}>일정 편집에서 이동 구간을 확인하면 조회 요금이 반영됩니다. 자동차는 차량1대의 통행료이며 연료·주차비는 추가 비용으로 입력하세요. 나이·할인·예약 조건에 따라 실제 금액이 달라질 수 있습니다.</p></div></details>
  {summary.outOfPeriod>0&&<p role="alert">여행 기간 밖 {summary.outOfPeriod}곳은 합계에서 제외됐어요. 일정에서 방문 날짜를 확인한 뒤 여행비를 저장해 주세요.</p>}{invalid&&<p role="alert">금액은 0원부터 1억원까지의 원 단위 정수로 입력해 주세요.</p>}{conflict&&<p role="alert">다른 창에서 여행비가 변경됐어요. 최신 내용을 불러온 뒤 다시 편집해 주세요.</p>}
  <div className="travel-book-actions"><button type="button" disabled={!ready||invalid||conflict||!dirty||Boolean(summary.outOfPeriod)} onClick={save}>여행비 저장</button><button type="button" disabled={!dirty&&!conflict} onClick={reload}>저장한 내용으로 되돌리기</button><button type="button" disabled={!ready||invalid||Boolean(summary.outOfPeriod)} onClick={exportText}>여행비 요약 저장</button></div><p role="status">{notice}</p>
 </section>;
}
export default function TripBudget(props:Props){return <BudgetForm key={budgetIdentity(props.trip.orderedSavedPlaces,props.trip.tripDays)} {...props}/>;}
