import { expect, test } from '@playwright/test';
import { mockPlannerApi } from './fixtures';
import { openSupportMenu } from './support-menu';

test('support and nested preferences expose named controls and restore keyboard focus', async ({ page }) => {
  await mockPlannerApi(page);
  await page.goto('/planner');
  await openSupportMenu(page);
  const support = page.locator('.wave-support-menu');
  const trigger = support.getByRole('button', { name: 'WAVE 이용 안내 메뉴', exact: true });
  await expect(trigger).toHaveAttribute('aria-expanded', 'true');
  await expect(support.getByRole('link', { name: '사용 가이드', exact: true })).toBeVisible();
  const preferences = support.getByRole('button', { name: '환경설정 열기', exact: true });
  await preferences.focus();
  await page.keyboard.press('Enter');
  await expect(preferences).toHaveAttribute('aria-expanded', 'true');
  const panel = page.locator('.preference-panel');
  await expect(panel.getByRole('radio', { name: /기본/ })).toBeVisible();
  const textSize = panel.getByRole('radio', { name: /크게.*18px/ });
  await textSize.focus();
  await page.keyboard.press('Space');
  await expect(textSize).toBeChecked();
  await page.keyboard.press('Escape');
  await expect(panel).toHaveCount(0);
  await expect(preferences).toBeFocused();
  await expect(trigger).toHaveAttribute('aria-expanded', 'true');
  await page.keyboard.press('Escape');
  await expect(trigger).toBeFocused();
  await expect(trigger).toHaveAttribute('aria-expanded', 'false');
  await expect(page.locator('.wave-support-panel')).toHaveCount(0);
  await page.keyboard.press('Enter');
  const help = support.getByRole('button', { name: '도움말', exact: true });
  await help.click();
  await expect(page.locator('.help-tour-dialog')).toBeVisible();
  await expect(support).toHaveAttribute('data-open', 'false');
  await page.getByRole('button', { name: '도움말 닫기', exact: true }).click();
  await expect(help).toBeFocused();
});

test('festival facility choices retain names and selection through keyboard close and reopen', async ({ page }) => {
  await mockPlannerApi(page);
  await page.route('**/api/festivals?**', route => route.fulfill({ json: {items:[], state:'live', partial:false, checkedAt:'2026-09-21T00:00:00Z'} }));
  await page.goto('/festivals');
  const mobile = page.getByRole('button', { name: '축제 검색 조건', exact: false });
  if (await mobile.isVisible()) await mobile.click();
  await expect(page.getByLabel('언제부터', { exact: true })).not.toHaveValue('');
  const trigger = page.getByRole('button', { name: /^접근성 조건/ });
  await trigger.focus();
  await page.keyboard.press('Enter');
  await expect(trigger).toHaveAttribute('aria-expanded', 'true');
  const panel = page.locator('.festival-preference-panel');
  const choices = panel.getByRole('button');
  expect(await choices.count()).toBeGreaterThan(0);
  for (const choice of await choices.all()) await expect(choice).toHaveAccessibleName(/\S/);
  const first = choices.first();
  const label = await first.getAttribute('aria-label');
  const selected = await first.getAttribute('aria-pressed');
  await first.focus();
  await page.keyboard.press('Space');
  await expect(first).toHaveAttribute('aria-pressed', selected === 'true' ? 'false' : 'true');
  await page.keyboard.press('Escape');
  await expect(trigger).toBeFocused();
  await expect(panel).toHaveCount(0);
  await page.keyboard.press('Enter');
  await expect(panel.getByRole('button', { name: label!, exact: true })).toHaveAttribute('aria-pressed', selected === 'true' ? 'false' : 'true');
  await choices.last().focus();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('button', { name: '축제 검색하기', exact: false })).toBeFocused();
  await expect(trigger).toHaveAttribute('aria-expanded', 'false');
});
