import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { chooseTripConditions, mockPlannerApi, mockPublicShellApi } from "./fixtures";

test("fixed visits keep their date and order, and return deadlines follow the live schedule", async ({ page }, info) => {
  await mockPublicShellApi(page); await mockPlannerApi(page, { preserveView: true });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.addInitScript(() => { if (!localStorage.getItem("wave-trip-schedule-v1")) localStorage.setItem("wave-trip-schedule-v1", JSON.stringify({ travelStart: "2026-09-14", travelEnd: "2026-09-15", dayStartTime: "10:00", scheduleAssignments: {} })); });
  const errors: string[] = [], shares: Array<Record<string, unknown>> = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/trips", route => { shares.push(route.request().postDataJSON().selections); return route.fulfill({ json: { url: `${new URL(route.request().url()).origin}/trip/123456789abc` } }); });
  await page.goto("/planner"); await chooseTripConditions(page);
  await page.getByRole("button", { name: "경남도립미술관 일정에 추가", exact: true }).click();
  await page.getByRole("button", { name: "용지호수공원 일정에 추가", exact: true }).click();
  await page.locator(".reference-journey-views button").nth(1).click();
  const board = page.locator(".reference-day-list");
  await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  await board.getByLabel("경남도립미술관 장소 고정", { exact: true }).selectOption("event");
  await board.getByLabel("경남도립미술관 고정 도착 시각", { exact: true }).fill("13:00");
  await expect(board.locator(".reference-stop > time").first()).toHaveText("13:00");
  await expect(board).toContainText("고정 시각 전");
  await expect(board.getByLabel("경남도립미술관 여행 날짜", { exact: true })).toBeDisabled();
  await expect(board.getByLabel("경남도립미술관 같은 날 뒤 순서로 이동", { exact: true })).toBeDisabled();
  await expect(board.locator(".reference-stop-actions").first().getByRole("button", { name: "일정에서 제거", exact: true })).toBeDisabled();
  await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  const deadline = board.locator(".day-deadline"), summary = deadline.locator("summary");
  await summary.click();
  await deadline.getByLabel("도착 마감 시각", { exact: true }).fill("18:00");
  await deadline.getByRole("button", { name: "적용", exact: true }).click();
  await expect(summary).toBeFocused();
  await expect(deadline).toContainText("귀가 이동시간 확인 필요");
  await summary.click();
  await deadline.getByLabel("마지막 장소부터 이동 (분, 선택)", { exact: true }).fill("721");
  await deadline.getByRole("button", { name: "적용", exact: true }).click();
  await expect(deadline.getByRole("alert")).toBeVisible();
  await deadline.getByLabel("마지막 장소부터 이동 (분, 선택)", { exact: true }).fill("30");
  await deadline.getByLabel("마지막 장소부터 이동 (분, 선택)", { exact: true }).press("Enter");
  await expect(deadline).toContainText("계획상");
  await board.locator(".reference-start-time input").fill("17:00");
  await expect(board).toContainText("도착 예상"); await expect(deadline).toContainText("초과 예상");
  await board.locator(".reference-start-time input").fill("10:00");
  await summary.click(); await deadline.getByLabel("도착 마감 시각", { exact: true }).fill("12:00");
  await deadline.getByLabel("도착 마감 시각", { exact: true }).press("Escape"); await expect(summary).toBeFocused();
  await expect(summary).toContainText("18:00");
  await board.getByRole("button", { name: /DAY 2/ }).click();
  await expect(deadline.locator(".day-deadline-summary")).toHaveCount(0);
  await summary.click();
  await deadline.getByLabel("도착 마감 시각", { exact: true }).fill("20:00");
  await deadline.getByLabel("마지막 장소부터 이동 (분, 선택)", { exact: true }).fill("0");
  await deadline.getByRole("button", { name: "적용", exact: true }).click();
  await expect(summary).toContainText("20:00");
  await summary.click(); await deadline.getByRole("button", { name: "마감 해제", exact: true }).click();
  await board.getByRole("button", { name: /DAY 1/ }).click();
  const widths = info.project.name.startsWith("desktop") ? [1440, 960] : [390, 320];
  for (const width of widths) {
    await page.setViewportSize({ width, height: 960 });
    await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
    await board.getByLabel("경남도립미술관 장소 고정", { exact: true }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: info.outputPath(`fixed-${width}.png`) });
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    expect((await new AxeBuilder({ page }).include(".reference-day-list").analyze()).violations).toEqual([]);
    await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  }
  await page.reload(); await expect(board.locator(".reference-stop > time").first()).toHaveText("13:00");
  await expect(deadline).toContainText("18:00");
  await page.getByRole("button", { name: "다음: 전체보기", exact: true }).click();
  await page.getByRole("button", { name: "공유하기", exact: true }).click();
  await expect(page.getByRole("link", { name: "공유 일정 열기", exact: true })).toBeVisible();
  expect(shares[0].fixedVisits).toEqual({ "1001": { kind: "event", time: "13:00", position: 0 } });
  expect(shares[0].dayDeadlines).toEqual({ "2026-09-14": { time: "18:00", returnMinutes: 30, bufferMinutes: 15 } });
  await page.locator(".reference-final-actions").getByRole("button", { name: "내 일정에 저장", exact: true }).click();
  await page.goto("/travel-book"); await page.getByRole("button", { name: /이 일정 다시 열기/ }).click();
  await expect(board.locator(".reference-stop > time").first()).toHaveText("13:00"); await expect(deadline).toContainText("18:00");
  await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  await board.getByLabel("경남도립미술관 장소 고정", { exact: true }).selectOption("");
  await expect(board.getByLabel("경남도립미술관 여행 날짜", { exact: true })).toBeEnabled();
  await expect(board.locator(".reference-stop > time").first()).not.toHaveText("13:00");
  expect(errors).toEqual([]);
});
