import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mockPlannerApi, openItinerary } from './fixtures';

test.use({ storageState: { cookies: [], origins: [] } });

test('여행 설정의 부분 날짜 입력은 일정을 바꾸거나 화면을 닫지 않고 수정·취소할 수 있다', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await mockPlannerApi(page, { preserveView: true });
  await page.goto('/planner?region=창원');
  await page.getByRole('button', { name: '경남도립미술관 일정에 담기', exact: true }).click();
  await openItinerary(page, { start: '2026-10-03' });
  await page.getByRole('button', { name: '여행 설정', exact: true }).click();
  const settings = page.getByRole('dialog', { name: '여행 설정', exact: true });
  const start = settings.getByLabel('시작일', { exact: true });
  const end = settings.getByLabel('마지막 날', { exact: true });
  await start.fill('');
  await start.pressSequentially('2026-09-2');
  await expect(start).toHaveValue('2026-09-2');
  expect(await start.evaluate((node: HTMLInputElement) => node.checkValidity())).toBe(false);
  await settings.getByRole('button', { name: '적용', exact: true }).click();
  await expect(settings).toBeVisible();
  await expect(end).toHaveValue('2026-10-03');
  await start.fill('2026-10-05');
  await expect(end).toHaveValue('2026-10-05');
  await start.press('Alt+ArrowDown');
  const calendar = page.getByRole('dialog', { name: '시작일 날짜 선택', exact: true });
  await expect(calendar).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(calendar).not.toBeVisible();
  await expect(settings).toBeVisible();
  await expect(settings.getByRole('button', { name: '시작일 달력 열기', exact: true })).toBeFocused();
  await settings.getByRole('button', { name: '취소', exact: true }).click();
  await page.getByRole('button', { name: '여행 설정', exact: true }).click();
  await expect(start).toHaveValue('2026-10-03');
  expect(errors).toEqual([]);
});

test('축제 달력은 밤 테마와 키보드 탐색, 날짜 하한, 닫기 초점을 유지한다', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-26T03:00:00.000Z'));
  await page.route('**/api/**', route => route.fulfill({ status: 200, json: { items: [], state: 'live', checkedAt: '2026-09-26T03:00:00.000Z' } }));
  await page.goto('/festivals');
  if (page.viewportSize()!.width <= 600) await page.getByRole('button', { name: '축제 검색 조건', exact: false }).click();
  await expect(page.getByLabel('언제부터', { exact: true })).toHaveValue('2026-09-26');
  const opener = page.getByRole('button', { name: '언제부터 달력 열기', exact: true });
  await opener.click();
  const dialog = page.getByRole('dialog', { name: '언제부터 날짜 선택' });
  await expect(dialog).toBeVisible();
  await expect(dialog).toHaveCSS('border-radius', '24px');
  expect((await new AxeBuilder({ page }).include('.wave-date-dialog[open]').analyze()).violations).toEqual([]);
  const day = dialog.locator('[data-date="2026-09-26"]');
  await expect(day).toBeFocused();
  await day.press('ArrowRight');
  await expect(dialog.locator('[data-date="2026-09-27"]')).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(dialog).not.toBeVisible();
  await expect(page.getByLabel('언제부터', { exact: true })).toHaveValue('2026-09-27');
  await expect(opener).toBeFocused();
  await page.getByRole('button', { name: '언제까지 달력 열기', exact: true }).click();
  const endDialog = page.getByRole('dialog', { name: '언제까지 날짜 선택' });
  await endDialog.getByRole('button', { name: '이전 달', exact: true }).click();
  await expect(endDialog.locator('[data-date="2026-09-26"]')).toBeDisabled();
  await expect(endDialog.locator('[data-date="2026-09-27"]')).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(endDialog).not.toBeVisible();
  await expect(page.getByRole('button', { name: '언제까지 달력 열기', exact: true })).toBeFocused();
});

test('나루 날짜 입력은 달력 선택 이벤트와 필수·날짜 범위 검증을 유지한다', async ({ page }) => {
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: {} }));
  await mockPlannerApi(page);
  await page.goto('/planner?region=창원');
  await page.getByRole('button', { name: 'WAVE 여행 가이드 나루와 대화 열기', exact: true }).click();
  const panel = page.getByRole('dialog', { name: 'WAVE 여행 가이드 나루와 대화', exact: true });
  await panel.getByRole('button', { name: '여행 준비 맡기기', exact: true }).click();
  const form = panel.getByRole('form', { name: '여행 준비 맡기기', exact: true });
  const start = form.getByLabel('출발 날짜', { exact: true });
  const end = form.getByLabel('마지막 날짜', { exact: true });
  await start.fill('2026-10-03');
  await end.fill('2026-10-04');
  await start.press('Alt+ArrowDown');
  const calendar = page.getByRole('dialog', { name: '출발 날짜 날짜 선택' });
  await expect(calendar).toBeVisible();
  await calendar.locator('[data-date="2026-10-05"]').click();
  await expect(start).toHaveValue('2026-10-05');
  // The caller's onChange also advances the end date, proving a real React change event.
  await expect(end).toHaveValue('2026-10-05');
  await end.fill('2026-10-04');
  expect(await end.evaluate((node: HTMLInputElement) => node.checkValidity())).toBe(false);
  await start.fill('2026-02-30');
  expect(await start.evaluate((node: HTMLInputElement) => node.checkValidity())).toBe(false);
  await start.fill('');
  expect(await start.evaluate((node: HTMLInputElement) => node.validity.valueMissing)).toBe(true);
  await start.fill('2026-10-03');
  await start.press('Alt+ArrowDown');
  await page.keyboard.press('Escape');
  await expect(calendar).not.toBeVisible();
  await expect(panel).toBeVisible();
});
