import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { chooseTripConditions, mockPlannerApi, mockPublicShellApi } from "./fixtures";

test("8+10 시안: 지역부터 날짜·일정·전체보기까지 실제 저장 흐름을 유지한다", async ({ page }, info) => {
  await mockPublicShellApi(page);
  await mockPlannerApi(page, { plannerView: "guided" });
  await page.emulateMedia({ reducedMotion: "reduce" });
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.route("**/api/trips", route => route.fulfill({ json: { url: `${new URL(route.request().url()).origin}/trip/pdf-design-example` } }));
  await page.goto("/planner");
  await expect(page.getByRole("heading", { name: "경남, 어디부터 가볼까요?" })).toBeVisible();
  await expect(page.locator(".planner-navigation nav button")).toHaveCount(5);
  await expect(page.getByRole("button", { name: "통영 지역 선택" })).toBeVisible();
  await page.screenshot({ path: info.outputPath("pdf-region.png"), fullPage: true });
  await chooseTripConditions(page);
  const filters = page.getByRole("group", { name: "여행지 결과 필터" });
  await filters.getByRole("button", { name: "실내", exact: true }).click();
  await expect(page.locator(".place-carousel .place-card")).toHaveCount(1);
  await filters.getByRole("button", { name: "조건 확인만", exact: true }).click();
  await expect(page.locator(".place-carousel .place-card")).toHaveCount(0);
  await filters.getByRole("button", { name: "추천순", exact: true }).click();
  await expect(page.locator(".place-carousel .place-card")).toHaveCount(2);
  await page.screenshot({ path: info.outputPath("pdf-places.png"), fullPage: true });
  await page.getByRole("button", { name: "경남도립미술관 일정에 추가", exact: true }).click();
  await page.locator(".planner-nav-context > button").nth(1).click();
  await expect(page.getByRole("heading", { name: "언제 떠날까요?", exact: true })).toBeVisible();
  const fields = page.locator(".reference-date-fields");
  const existing = await fields.getByLabel("출발일").inputValue();
  const start = new Date(`${existing}T12:00:00`); start.setDate(start.getDate() + 3);
  const end = new Date(start); end.setDate(end.getDate() + 1);
  const local = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
  await fields.getByLabel("출발일").fill(local(start));
  await fields.getByLabel("도착일").fill(local(end));
  await expect(page.getByText("기존 날짜에 남아 있는 여행지 1곳이 있어요.")).toBeVisible();
  await page.getByRole("button", { name: "이 1곳을 새 출발일로 옮기기" }).click();
  await expect(page.locator(".reference-date-summary ol li")).toHaveCount(2);
  await page.screenshot({ path: info.outputPath("pdf-dates.png"), fullPage: true });
  await page.getByRole("button", { name: "다음: 일정 만들기", exact: true }).click();
  const board = page.locator(".reference-day-list");
  await expect(board.getByRole("button", { name: "경남도립미술관", exact: true })).toBeVisible();
  // A changed date preserves saved visits but must refresh old recommendations
  // before another place can be added under the new trip conditions.
  await expect(page.getByRole("button", { name: "용지호수공원 일정에 추가", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "선택한 조건으로 여행지 찾기", exact: true }).click();
  await page.getByRole("button", { name: "용지호수공원 일정에 추가", exact: true }).click();
  await page.locator(".planner-navigation nav button").nth(3).click();
  await expect(board.locator(".reference-stop")).toHaveCount(2);
  await board.getByRole("button", { name: "용지호수공원 같은 날 앞 순서로 이동" }).click();
  await expect(board.locator(".reference-stop-copy > button").first()).toHaveText("용지호수공원");
  await board.getByLabel("하루 시작").fill("09:30");
  await page.screenshot({ path: info.outputPath("pdf-itinerary.png"), fullPage: true });
  await page.getByRole("button", { name: "지도 함께 보기", exact: true }).click();
  await expect(page.locator(".reference-board-map .map-panel")).toBeVisible();
  await expect(page.locator(".reference-board-map .leaflet-container")).toBeVisible();
  await page.screenshot({ path: info.outputPath("pdf-map.png"), fullPage: true });
  await page.getByRole("button", { name: "다음: 전체보기", exact: true }).click();
  await expect(page.locator(".reference-overview .reference-schedule li")).toHaveCount(2);
  await page.getByRole("button", { name: "공유하기", exact: true }).click();
  await expect(page.getByRole("link", { name: "공유 일정 열기", exact: true })).toBeVisible();
  await page.locator(".reference-final-actions").getByRole("button", { name: "내 일정에 저장", exact: true }).click();
  await expect(page.locator(".reference-archive [role=status]")).toContainText("내 일정에 저장했어요");
  const widths = info.project.name.startsWith("desktop") ? [1440, 960] : [390];
  for (const width of widths) {
    await page.setViewportSize({ width, height: 960 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
    await page.screenshot({ path: info.outputPath(`pdf-overview-${width}.png`), fullPage: true });
  }
  expect((await new AxeBuilder({ page }).include(".reference-overview").analyze()).violations).toEqual([]);
  expect(errors).toEqual([]);
});
