import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mockPublicShellApi,mockPlannerApi,chooseTripConditions} from './fixtures';
import {alternativePlan} from './alternative-fixtures';
const plan={...alternativePlan,explorationPlaces:[{...alternativePlan.places[2],id:'1010',name:'편의 미확인 공원',accessibility:alternativePlan.places[2].accessibility?.map(field=>({...field,state:'unknown'}))}]};
async function setup(page:Page){await mockPublicShellApi(page);await mockPlannerApi(page,{preserveView:true});await page.emulateMedia({reducedMotion:'reduce'});await page.route('**/api/wave?action=plan*',route=>route.fulfill({json:plan}));}
test('anchor expansion previews one nearby stop, preserves the period, and undoes the exact addition',async({page},info)=>{
 await setup(page);await page.goto('/planner');await chooseTripConditions(page);await page.getByRole('button',{name:'경남도립미술관 일정에 추가',exact:true}).click();await page.locator('.reference-journey-views button').nth(1).click();
 await page.getByText('한 장소에서 코스 이어 담기',{exact:true}).click();const panel=page.getByRole('region',{name:'한 장소에서 코스 확장',exact:true});
 const before=await page.locator('.reference-day-list').innerText();
 const candidate=panel.getByRole('article').filter({has:page.getByRole('heading',{name:'용지호수공원',exact:true})});await candidate.getByRole('button',{name:'추가 미리보기',exact:true}).click();
 await expect(panel.getByRole('heading',{name:'경남도립미술관 → 용지호수공원',exact:true})).toBeFocused();await expect.poll(()=>page.locator('.reference-day-list').innerText()).toBe(before);
 await panel.getByRole('button',{name:'이 장소 이어 담기',exact:true}).click();await expect(page.locator('.reference-day-list')).toContainText('용지호수공원');await panel.getByRole('button',{name:'방금 이어 담기 되돌리기',exact:true}).click();await expect.poll(()=>page.locator('.reference-day-list').innerText()).toBe(before);
 await panel.getByLabel('필요한 편의가 미확인인 곳도 살펴보기',{exact:true}).check();await expect(panel).toContainText('편의 미확인 공원');
 for(const width of info.project.name.includes('desktop')?[1440,960]:[390,320]){await page.setViewportSize({width,height:960});await panel.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`course-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);expect((await new AxeBuilder({page}).include('[aria-label="한 장소에서 코스 확장"]').analyze()).violations).toEqual([]);}
});
test('a later pinned stop blocks course insertion and a new pin prevents undoing an edited addition',async({page})=>{
 await setup(page);await page.goto('/planner');await chooseTripConditions(page);for(const name of ['경남도립미술관','용지호수공원'])await page.getByRole('button',{name:name+' 일정에 추가',exact:true}).click();await page.locator('.reference-journey-views button').nth(1).click();
 const board=page.locator('.reference-day-list');await board.getByLabel('용지호수공원 일정 수정',{exact:true}).click();await board.getByLabel('용지호수공원 장소 고정',{exact:true}).selectOption('visit');await board.getByLabel('용지호수공원 일정 수정',{exact:true}).click();
 await page.getByText('한 장소에서 코스 이어 담기',{exact:true}).click();const panel=page.getByRole('region',{name:'한 장소에서 코스 확장',exact:true});await panel.getByRole('combobox',{name:'어느 장소 다음에 갈까요?',exact:true}).selectOption('1001');
 const park=panel.getByRole('article').filter({has:page.getByRole('heading',{name:'강변정원',exact:true})});await park.getByRole('button',{name:'추가 미리보기',exact:true}).click();await panel.getByRole('button',{name:'이 장소 이어 담기',exact:true}).click();await expect(panel).toContainText('고정 일정의 순서나 날짜를 지키기 위해 추가하지 않았어요');await expect(board.locator('.reference-stop')).toHaveCount(2);
 await board.getByLabel('용지호수공원 일정 수정',{exact:true}).click();await board.getByLabel('용지호수공원 장소 고정',{exact:true}).selectOption('');await board.getByLabel('용지호수공원 일정 수정',{exact:true}).click();await panel.getByRole('button',{name:'이 장소 이어 담기',exact:true}).click();await expect(board.locator('.reference-stop')).toHaveCount(3);
 await board.getByLabel('강변정원 일정 수정',{exact:true}).click();await board.getByLabel('강변정원 장소 고정',{exact:true}).selectOption('visit');await board.getByLabel('강변정원 일정 수정',{exact:true}).click();await panel.getByRole('button',{name:'방금 이어 담기 되돌리기',exact:true}).click();await expect(panel).toContainText('추가한 뒤 일정이 바뀌었어요');await expect(board.locator('.reference-stop')).toHaveCount(3);
});
test('a short outing has explicit search, time limits, separate save and retained main itinerary',async({page},info)=>{
 await setup(page);await page.addInitScript(()=>{localStorage.setItem('wave-saved-places','["2758443"]');localStorage.setItem('wave-trip-schedule-v1',JSON.stringify({travelStart:'2026-10-02',travelEnd:'2026-10-03',dayStartTime:'09:30',scheduleAssignments:{'2758443':'2026-10-02'}}));sessionStorage.setItem('wave-outing-entry-v1',JSON.stringify({region:'창원',theme:'nature',profiles:['wheel'],createdAt:Date.now()}));});
 let calls=0;await page.route('**/api/wave?action=plan*',route=>{calls++;return route.fulfill({json:plan});});
 await page.goto('/outings');await expect(page.getByRole('button',{name:'✓ 휠체어 편의시설',exact:true})).toHaveAttribute('aria-pressed','true');expect(calls).toBe(0);const before=await page.evaluate(()=>localStorage.getItem('wave-trip-schedule-v1'));
 await page.getByLabel('여행 날짜',{exact:true}).fill('2026-10-08');await page.getByRole('button',{name:'이 시간에 나들이 찾기',exact:true}).click();await expect(page.getByRole('heading',{name:'잠깐 머물고 싶은 곳',exact:true})).toBeFocused();expect(calls).toBe(1);
 for(const name of ['경남도립미술관','용지호수공원']){const choice=page.getByRole('button',{name:name+' 나들이에 담기',exact:true});if(!await choice.count())await page.getByRole('button',{name:'다음 후보',exact:true}).click();await choice.click();}await page.getByRole('button',{name:'이 나들이 살펴보기',exact:true}).click();const review=page.getByRole('region',{name:'짧은 나들이 일정 확인',exact:true});await expect(review).toContainText('창원중앙역');
 await review.getByRole('button',{name:'짧은 나들이 저장',exact:true}).click();await expect(review).toContainText('짧은 나들이를 내 일정에 저장했어요');expect(await page.evaluate(()=>localStorage.getItem('wave-trip-schedule-v1'))).toBe(before);const books=await page.evaluate(()=>JSON.parse(localStorage.getItem('wave-travel-book-v1')||'[]'));expect(books).toHaveLength(1);expect(books[0].note).toContain('창원중앙역');expect(books[0].places).toHaveLength(2);expect(books[0].visitMinutesByPlaceId['1001']).toBe(45);
 for(const width of info.project.name.includes('desktop')?[1440,960]:[390,320]){await page.setViewportSize({width,height:960});await review.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`outing-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);expect((await new AxeBuilder({page}).include('main').analyze()).violations).toEqual([]);}
 await page.getByRole('button',{name:'조건 다시 정하기',exact:true}).click();await page.getByRole('combobox',{name:'쓸 수 있는 시간',exact:true}).selectOption('1');await expect(review).toHaveCount(0);await expect(page.getByRole('button',{name:'이 나들이 살펴보기',exact:true})).toHaveCount(0);expect(calls).toBe(1);
});
test('outing provider errors, changed preferences and blocked storage keep truthful state',async({page})=>{
 await setup(page);await page.goto('/outings');await page.getByRole('button',{name:'휠체어 편의시설',exact:true}).click();await page.getByLabel('여행 날짜',{exact:true}).fill('2026-10-08');
 await page.route('**/api/wave?action=plan*',route=>route.fulfill({status:502,json:{error:'Unavailable'}}));await page.getByRole('button',{name:'이 시간에 나들이 찾기',exact:true}).click();await expect(page.getByRole('status')).toContainText('여행 후보를 불러오지 못했어요');await expect(page.getByRole('region',{name:'짧은 나들이 장소 고르기'})).toHaveCount(0);
 await page.route('**/api/wave?action=plan*',route=>route.fulfill({json:plan}));await page.getByRole('button',{name:'이 시간에 나들이 찾기',exact:true}).click();await page.getByRole('button',{name:'경남도립미술관 나들이에 담기',exact:true}).click();await page.getByRole('button',{name:'이 나들이 살펴보기',exact:true}).click();
 await page.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='wave-travel-book-v1')throw new DOMException('Full','QuotaExceededError');return original.call(this,key,value);};});await page.getByRole('button',{name:'짧은 나들이 저장',exact:true}).click();await expect(page.getByRole('region',{name:'짧은 나들이 일정 확인'})).toContainText('일정을 저장하지 못했어요');
 await page.getByRole('button',{name:'조건 다시 정하기',exact:true}).click();await page.getByRole('combobox',{name:'여행 지역',exact:true}).selectOption('통영');await expect(page.getByRole('region',{name:'짧은 나들이 장소 고르기'})).toHaveCount(0);await expect(page.getByRole('region',{name:'짧은 나들이 일정 확인'})).toHaveCount(0);
});
