import fs from 'node:fs/promises';
import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mockPublicShellApi, mockPlannerApi, chooseTripConditions } from './fixtures';
import { alternativePlan } from './alternative-fixtures';
const day='2026-10-08';
async function setup(page:Page){
 await mockPublicShellApi(page);await mockPlannerApi(page,{preserveView:true});await page.emulateMedia({reducedMotion:'reduce'});await page.route('**/api/wave?action=plan*',route=>route.fulfill({json:alternativePlan}));
 await page.addInitScript(()=>{if(localStorage.getItem('wave-trip-order-v1'))return;localStorage.setItem('wave-trip-order-v1',JSON.stringify({mode:'manual',ids:['1001','1002','1003']}));localStorage.setItem('wave-trip-schedule-v1',JSON.stringify({travelStart:'2026-10-08',travelEnd:'2026-10-09',dayStartTime:'10:00',scheduleAssignments:{1001:'2026-10-08',1002:'2026-10-08',1003:'2026-10-08'},visitMinutesByPlaceId:{1001:15,1002:30,1003:15},breakMinutesByPlaceId:{1002:15}}));});
 await page.goto('/planner');await chooseTripConditions(page);for(const name of ['경남도립미술관','용지호수공원','시민문화쉼터'])await page.getByRole('button',{name:name+' 일정에 추가',exact:true}).click();await page.locator('.reference-journey-views button').nth(1).click();await page.getByRole('button',{name:'다음: 전체보기',exact:true}).click();await page.getByRole('button',{name:'동행과 합류 계획',exact:true}).click();
}
const panel=(page:Page)=>page.getByRole('region',{name:'동행과 합류 계획',exact:true});
test('split/reunion saves an optional A/B plan, keeps original trip and exports explicit offline lines',async({page},info)=>{
 await setup(page);const tool=panel(page),before=await page.evaluate(()=>({saved:localStorage.getItem('wave-saved-places'),schedule:localStorage.getItem('wave-trip-schedule-v1'),order:localStorage.getItem('wave-trip-order-v1')}));
 await tool.getByRole('combobox',{name:'B 출발 장소에서 더 머무는 시간',exact:true}).selectOption('60');await page.getByRole('button',{name:'돌아가는 교통 확인',exact:true}).click();await page.getByRole('button',{name:'동행과 합류 계획',exact:true}).click();await expect(tool.getByRole('combobox',{name:'B 출발 장소에서 더 머무는 시간',exact:true})).toHaveValue('60');
 await tool.getByRole('combobox',{name:'합류를 계획할 날짜',exact:true}).selectOption('2026-10-09');await expect(tool).toContainText('세 곳 이상');await tool.getByRole('combobox',{name:'합류를 계획할 날짜',exact:true}).selectOption(day);await expect(tool.getByRole('combobox',{name:'B 출발 장소에서 더 머무는 시간',exact:true})).toHaveValue('60');
 await tool.getByRole('button',{name:'A·B 합류 계획 보기',exact:true}).click();await expect(tool.getByRole('heading',{name:'16:00, 시민문화쉼터에서 만나요',exact:true})).toBeFocused();await expect(tool.getByRole('region',{name:'A의 나뉜 일정'})).toContainText('체류 30분 · 휴식 15분');await expect(tool.getByRole('region',{name:'B의 나뉜 일정'})).toContainText('60분 더');
 await tool.getByRole('button',{name:'합류 약속 저장',exact:true}).click();await expect(tool.getByRole('status').filter({hasText:'합류 약속을 저장했어요'})).toBeVisible();
 for(const width of info.project.name.includes('desktop')?[1440,960]:[390,320]){await page.setViewportSize({width,height:960});await tool.getByRole('heading',{name:'16:00, 시민문화쉼터에서 만나요',exact:true}).scrollIntoViewIfNeeded();await page.evaluate(()=>scrollBy(0,-150));await page.screenshot({path:info.outputPath(`split-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);expect((await new AxeBuilder({page}).include('[aria-label="동행과 합류 계획"]').analyze()).violations).toEqual([]);}
 await page.getByRole('button',{name:'여행 요약 챙기기',exact:true}).click();const pack=page.getByRole('region',{name:'여행 요약 파일',exact:true});await pack.getByLabel('저장한 A·B 합류 약속 포함',{exact:true}).check();const event=page.waitForEvent('download');await pack.getByRole('button',{name:'텍스트로 저장',exact:true}).click();const file=info.outputPath('split-summary.txt');await(await event).saveAs(file);const text=await fs.readFile(file,'utf8');expect(text).toContain('따로 걷고 다시 함께');expect(text).toContain('A 일정');expect(text).toContain('B 일정');expect(text).toContain('휴식 15분');
 expect(await page.evaluate(()=>({saved:localStorage.getItem('wave-saved-places'),schedule:localStorage.getItem('wave-trip-schedule-v1'),order:localStorage.getItem('wave-trip-order-v1')}))).toEqual(before);
 await page.reload();await page.getByRole('button',{name:'동행과 합류 계획',exact:true}).click();await expect(tool.getByRole('combobox',{name:'B 출발 장소에서 더 머무는 시간',exact:true})).toHaveValue('60');
});
test('late plans, storage conflicts and changed original schedules never claim a valid saved plan',async({page})=>{
 await setup(page);const tool=panel(page);await tool.getByLabel('다시 만날 시각',{exact:true}).fill('12:10');await tool.getByRole('button',{name:'A·B 합류 계획 보기',exact:true}).click();await expect(tool.getByRole('button',{name:'합류 약속 저장',exact:true})).toBeDisabled();await expect(tool).toContainText('늦어요');
 await tool.getByLabel('다시 만날 시각',{exact:true}).fill('16:00');await tool.getByRole('button',{name:'A·B 합류 계획 보기',exact:true}).click();await tool.getByRole('button',{name:'합류 약속 저장',exact:true}).click();await expect(tool).toContainText('합류 약속을 저장했어요');
 await page.evaluate(()=>{const key='wave-split-reunion-v1',rows=JSON.parse(localStorage.getItem(key)||'[]');rows[0].savedAt='2026-10-01T10:00:00Z';localStorage.setItem(key,JSON.stringify(rows));});await tool.getByRole('combobox',{name:'B 출발 장소에서 더 머무는 시간',exact:true}).selectOption('15');await tool.getByRole('button',{name:'A·B 합류 계획 보기',exact:true}).click();await tool.getByRole('button',{name:'합류 약속 저장',exact:true}).click();await expect(tool).toContainText('저장하지 못했어요');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('wave-split-reunion-v1')||'[]')[0].choice.waitB)).toBe(0);
 await page.evaluate(()=>{const key='wave-trip-schedule-v1',state=JSON.parse(localStorage.getItem(key)||'{}');state.visitMinutesByPlaceId['1002']=60;localStorage.setItem(key,JSON.stringify(state));});await page.reload();await page.getByRole('button',{name:'동행과 합류 계획',exact:true}).click();await expect(tool.getByRole('button',{name:'바뀐 일정으로 다시 계획',exact:true})).toBeVisible();await expect(tool.getByRole('button',{name:'합류 약속 저장',exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'여행 요약 챙기기',exact:true}).click();const pack=page.getByRole('region',{name:'여행 요약 파일'});await pack.getByLabel('저장한 A·B 합류 약속 포함',{exact:true}).check();await pack.getByRole('button',{name:'텍스트로 저장',exact:true}).click();await expect(pack.getByRole('status')).toContainText('합류 약속');
});
