import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { chooseTripConditions, mockPlannerApi, mockPublicShellApi, openItinerary, plan } from "./fixtures";

test("visit duration recalculates the next stop and persists through sharing, archive and restoration", async ({ page }, info) => {
  await page.route("**/api/**", route => route.fulfill({ status: 503, json: { error: "Unconfigured synthetic API" } }));
  await mockPublicShellApi(page);
  await mockPlannerApi(page, { preserveView: true });
  await page.emulateMedia({ reducedMotion: "reduce" });
  const errors: string[] = [];
  const shares: Array<{ selections: { visitMinutesByPlaceId: Record<string, number> } }> = [];
  page.on("pageerror", error => errors.push(error.message));
  let shareRevision = 0;
  const expiresAt = Date.now() + 30 * 86_400_000;
  await page.route(/\/api\/trips(?:\/123456789abc)?$/, route => {
    const body = route.request().postDataJSON();
    if (!body.operation) { shares.push(body); shareRevision++; }
    return route.fulfill({ json: { id: "123456789abc", url: `${new URL(route.request().url()).origin}/trip/123456789abc`, revision: shareRevision, expiresAt, live: true } });
  });
  await page.goto("/planner");
  await chooseTripConditions(page);
  await page.getByRole("button", { name: "경남도립미술관 일정에 담기", exact: true }).click();
  await page.getByRole("button", { name: "용지호수공원 일정에 담기", exact: true }).click();
  await openItinerary(page, { start: "2026-10-07" });
  const board = page.locator(".simple-stops");
  await expect(board.locator(".simple-stop")).toHaveCount(2);
  await page.getByRole("button", { name: "여행 설정", exact: true }).click();
  const settings = page.getByRole("dialog", { name: "여행 설정", exact: true });
  await settings.getByRole("combobox", { name: "이동 수단", exact: true }).selectOption("car");
  await settings.getByRole("button", { name: "적용", exact: true }).click();
  await expect(board.locator(".simple-leg-time")).toHaveText(["여기까지 이동 25분", "여기까지 이동 25분"]);
  await page.evaluate(() => document.fonts.ready);
  const minute = (value: string) => Number(value.split(":")[0]) * 60 + Number(value.split(":")[1]);
  const previous = minute((await board.locator(".simple-stop > time").nth(1).textContent())!);
  await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  const editor = page.getByRole("dialog", { name: "경남도립미술관 수정", exact: true });
  const choice = editor.getByRole("combobox", { name: "경남도립미술관 머무는 시간", exact: true });
  await choice.selectOption("30");
  // A stop editor is a draft: the timetable changes only after Apply.
  expect(minute((await board.locator(".simple-stop > time").nth(1).textContent())!)).toBe(previous);
  await editor.getByRole("button", { name: "적용", exact: true }).click();
  await expect.poll(async () => minute((await board.locator(".simple-stop > time").nth(1).textContent())!)).toBe(previous - 90);
  await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  await choice.selectOption("custom");
  const minutes = editor.getByRole("spinbutton", { name: "체류시간(분)", exact: true });
  await minutes.fill("0");
  await expect(minutes).toHaveAttribute("aria-invalid", "true");
  await expect(editor.getByRole("button", { name: "시간 적용", exact: true })).toBeDisabled();
  await minutes.fill("137");
  await expect(minutes).not.toHaveAttribute("aria-invalid", "true");
  await editor.locator(".travel-book-actions").getByRole("button", { name: "취소", exact: true }).click();
  await expect(choice).toHaveValue("30");
  await choice.selectOption("custom");
  await minutes.fill("137");
  await minutes.press("Enter");
  await expect(choice).toHaveValue("saved");
  await expect(board.locator(".simple-stop-copy").first()).toContainText("30분 머묾");
  await editor.getByRole("button", { name: "적용", exact: true }).click();
  await expect(board.locator(".simple-stop-copy").first()).toContainText("137분 머묾");
  await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  await choice.selectOption("custom");
  const widths = info.project.name.startsWith("desktop") ? [1440, 960] : [390, 320];
  for (const width of widths) {
    await page.setViewportSize({ width, height: 960 });
    await page.screenshot({ path: info.outputPath(`duration-${width}.png`), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  }
  expect((await new AxeBuilder({ page }).include(".simple-stop-editor").analyze()).violations).toEqual([]);
  await editor.locator(".simple-editor-footer").getByRole("button", { name: "취소", exact: true }).click();
  await page.reload();
  await expect(board.locator(".simple-stop-copy").first()).toContainText("137분 머묾");
  expect((await new AxeBuilder({ page }).include(".simple-stops").analyze()).violations).toEqual([]);
  await page.getByRole("button", { name: "공유", exact: true }).click();
  await expect(page.getByRole("link", { name: "공유 일정 보기", exact: true })).toBeVisible();
  expect(shares[0].selections.visitMinutesByPlaceId).toEqual({ "1001": 137 });
  await page.getByRole("button", { name: "공유 닫기", exact: true }).click();
  await page.getByRole("button", { name: "내 여행에 저장", exact: true }).click();
  await expect(page.locator(".simple-save-control [role=status]")).toContainText("내 여행에 저장했어요");
  await page.goto("/travel-book");
  await expect(page.locator(".travel-book-days")).toContainText("체류 137분");
  await page.getByRole("button", { name: /이 일정 다시 열기/ }).click();
  await expect(board.locator(".simple-stop-copy").first()).toContainText("137분 머묾");
  await board.getByLabel("경남도립미술관 일정 수정", { exact: true }).click();
  await choice.selectOption("default");
  await expect(choice.locator("option:checked")).toHaveText("기본 · 약 120분");
  await editor.getByRole("button", { name: "적용", exact: true }).click();
  await expect(board.locator(".simple-stop-copy").first()).toContainText("120분 머묾");
  await expect.poll(async () => page.evaluate(() => JSON.parse(JSON.parse(localStorage.getItem("wave-current-trip-v1") || "{}").values["wave-trip-schedule-v1"]).visitMinutesByPlaceId)).toEqual({});
  expect(errors).toEqual([]);
});

test("account duration edits are saved explicitly and visible to companions", async ({ page }) => {
  const id = "12345678-1234-4123-8123-123456789012";
  await mockPublicShellApi(page);
  await page.route("**/api/auth/get-session", route => route.fulfill({ json: { user: { id: "owner", name: "여행자", email: "owner@example.com" }, session: { id: "session" } } }));
  let payload = { version: 1, title: "창원 나들이", region: "창원", travelStart: "2026-09-20", travelEnd: "2026-09-20", dayStartTime: "10:00", themes: ["nature"], placeIds: ["1001"], scheduleAssignments: { "1001": "2026-09-20" }, visitMinutesByPlaceId: { "1001": 45 }, note: "", status: "planned" };
  let role = "owner";
  await page.route("**/api/account/travel/**", route => {
    if (route.request().url().endsWith("/places")) return route.fulfill({ json: { places: [plan.places[0]], missing: 0 } });
    if (route.request().method() !== "GET") payload = route.request().postDataJSON().payload;
    return route.fulfill({ json: { id, payload, role, revision: 2, updatedAt: Date.now(), members: [], votes: [], comments: [], invitationActive: false } });
  });
  await page.goto(`/my-trips/${id}`);
  const choice = page.getByRole("combobox", { name: "경남도립미술관 머무는 시간", exact: true });
  await expect(choice).toHaveValue("saved");
  await choice.selectOption("60");
  expect(payload.visitMinutesByPlaceId["1001"]).toBe(45);
  await page.getByRole("button", { name: "변경 사항 저장", exact: true }).click();
  await expect(page.getByText("여행 변경 사항을 계정에 저장했어요.")).toBeVisible();
  expect(payload.visitMinutesByPlaceId["1001"]).toBe(60);
  role = "member";
  await page.reload();
  await expect(page.getByText("체류 60분", { exact: true })).toBeVisible();
  await expect(choice).toHaveCount(0);
});
