import { chooseWaveOption, waveSelectNative } from './wave-select-fixture';
import { acceptTripTimingWarning } from './trip-timing-fixtures';
import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { chooseTripConditions, mockPlannerApi, mockPublicShellApi, openItinerary, plan } from "./fixtures";

test("visit duration recalculates the next stop and persists through sharing, archive and restoration", async ({ page }, info) => {
  await page.route("**/api/**", route => route.fulfill({ status: 503, json: { error: "Unconfigured synthetic API" } }));
  await mockPublicShellApi(page);
  await mockPlannerApi(page, { preserveView: true });
  await page.emulateMedia({ reducedMotion: "reduce" });
  const errors: string[] = [];
  const shares: Array<{ selections: { visitMinutesByPlaceId: Record<string, number> } }> = [];
  page.on("pageerror", error => errors.push(error.message));
  let shareRevision = 0;
  const expiresAt = Date.now() + 30 * 86_400_000;
  await page.route(/\/api\/trips(?:\/123456789abc)?$/, route => {
    const body = route.request().postDataJSON();
    if (!body.operation) { shares.push(body); shareRevision++; }
    return route.fulfill({ json: { id: "123456789abc", url: `${new URL(route.request().url()).origin}/trip/123456789abc`, revision: shareRevision, expiresAt, live: true } });
  });
  await page.goto("/planner");
  await chooseTripConditions(page);
  await page.getByRole("button", { name: "경남도립미술관 일정에 담기", exact: true }).click();
  await page.getByRole("button", { name: "용지호수공원 일정에 담기", exact: true }).click();
  await openItinerary(page, { start: "2026-10-07" });
  const board = page.locator(".simple-stops");
  await expect(board.locator(".simple-stop")).toHaveCount(2);
  await page.getByRole("button", { name: "여행 설정", exact: true }).click();
  const settings = page.getByRole("dialog", { name: "여행 설정", exact: true });
  await chooseWaveOption(settings.getByRole("combobox", { name: "이동 수단", exact: true }), "car");
  await settings.getByRole("button", { name: "적용", exact: true }).click();
  await expect(board.locator(".simple-stop > time")).toHaveText(["10:25 도착 예정", "10:50 도착 예정"]);
  const movementArrival = await board.locator(".simple-stop > time").nth(1).innerText();
  const visits = page.locator('.simple-timing-mode details');
  await visits.getByText('방문 시간표', { exact: true }).click();
  const museumVisit = visits.locator('li').filter({ hasText: '경남도립미술관' });
  const lakeVisit = visits.locator('li').filter({ hasText: '용지호수공원' });
  await page.evaluate(() => document.fonts.ready);
  const minute = (value: string) => { const time = value.match(/(\d{2}):(\d{2})/)!; return Number(time[1]) * 60 + Number(time[2]); };
  const previous = minute((await lakeVisit.textContent())!);
  await page.getByRole("button", { name: "경남도립미술관 일정 수정", exact: true }).click();
  const editor = page.getByRole("dialog", { name: "경남도립미술관 수정", exact: true });
  const choice = editor.getByRole("combobox", { name: "경남도립미술관 머무는 시간", exact: true });
  await chooseWaveOption(choice, "30");
  // A stop editor is a draft: the timetable changes only after Apply.
  expect(minute((await lakeVisit.textContent())!)).toBe(previous);
  await editor.getByRole("button", { name: "적용", exact: true }).click();
  await expect.poll(async () => minute((await lakeVisit.textContent())!)).toBe(previous - 90);
  await expect(board.locator(".simple-stop > time").nth(1)).toHaveText(movementArrival);
  await page.getByRole("button", { name: "경남도립미술관 일정 수정", exact: true }).click();
  await chooseWaveOption(choice, "custom");
  const minutes = editor.getByRole("spinbutton", { name: "체류시간(분)", exact: true });
  await minutes.fill("0");
  await expect(minutes).toHaveAttribute("aria-invalid", "true");
  await expect(editor.getByRole("button", { name: "시간 적용", exact: true })).toBeDisabled();
  await minutes.fill("137");
  await expect(minutes).not.toHaveAttribute("aria-invalid", "true");
  await editor.locator(".travel-book-actions").getByRole("button", { name: "취소", exact: true }).click();
  await expect(waveSelectNative(choice)).toHaveValue("30");
  await chooseWaveOption(choice, "custom");
  await minutes.fill("137");
  await minutes.press("Enter");
  await expect(waveSelectNative(choice)).toHaveValue("saved");
  await expect(museumVisit).toContainText("관람 30분");
  await editor.getByRole("button", { name: "적용", exact: true }).click();
  await expect(museumVisit).toContainText("관람 137분");
  await page.getByRole("button", { name: "경남도립미술관 일정 수정", exact: true }).click();
  await chooseWaveOption(choice, "custom");
  const widths = info.project.name.startsWith("desktop") ? [1440, 960] : [390, 320];
  for (const width of widths) {
    await page.setViewportSize({ width, height: 960 });
    await page.screenshot({ path: info.outputPath(`duration-${width}.png`), fullPage: true });
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  }
  expect((await new AxeBuilder({ page }).include(".simple-stop-editor").analyze()).violations).toEqual([]);
  await editor.locator(".simple-editor-footer").getByRole("button", { name: "취소", exact: true }).click();
  await page.reload();
  await visits.getByText('방문 시간표', { exact: true }).click();
  await expect(museumVisit).toContainText("관람 137분");
  expect((await new AxeBuilder({ page }).include(".simple-stops").analyze()).violations).toEqual([]);
  await page.getByRole("button", { name: "공유", exact: true }).click();
  { const create = page.getByRole('button', { name: '공개 링크 만들기', exact: true }); if (await create.isVisible() && await create.isEnabled()) { await create.click(); await acceptTripTimingWarning(page); } }
  await expect(page.getByRole("link", { name: "공유 일정 보기", exact: true })).toBeVisible();
  expect(shares[0].selections.visitMinutesByPlaceId).toEqual({ "1001": 137 });
  await page.getByRole("button", { name: "공유 닫기", exact: true }).click();
  await page.getByRole("button", { name: "내 여행에 저장", exact: true }).click();
  await expect(page.locator(".simple-save-control [role=status]")).toContainText("내 여행에 저장했어요");
  await page.goto("/travel-book");
  await page.getByText('일정과 메모 보기', { exact: true }).click();
  await expect(page.locator(".travel-book-days")).toContainText("체류 137분");
  await page.getByRole("button", { name: '일정 열기', exact: true }).click();
  await visits.getByText('방문 시간표', { exact: true }).click();
  await expect(museumVisit).toContainText("관람 137분");
  await page.getByRole("button", { name: "경남도립미술관 일정 수정", exact: true }).click();
  await chooseWaveOption(choice, "default");
  await expect(waveSelectNative(choice).locator("option:checked")).toHaveText("기본 · 약 120분");
  await editor.getByRole("button", { name: "적용", exact: true }).click();
  await expect(museumVisit).toContainText("관람 120분");
  await expect.poll(async () => page.evaluate(() => JSON.parse(JSON.parse(localStorage.getItem("wave-current-trip-v1") || "{}").values["wave-trip-schedule-v1"]).visitMinutesByPlaceId)).toEqual({});
  expect(errors).toEqual([]);
});

test("account duration edits are saved explicitly and visible to companions", async ({ page }) => {
  const id = "12345678-1234-4123-8123-123456789012";
  await mockPublicShellApi(page);
  await page.route("**/api/auth/get-session", route => route.fulfill({ json: { user: { id: "owner", name: "여행자", email: "owner@example.com" }, session: { id: "session" } } }));
  let payload = { version: 1, title: "창원 나들이", region: "창원", travelStart: "2026-09-20", travelEnd: "2026-09-20", dayStartTime: "10:00", themes: ["nature"], placeIds: ["1001"], scheduleAssignments: { "1001": "2026-09-20" }, visitMinutesByPlaceId: { "1001": 45 }, note: "", status: "planned" };
  let role = "owner";
  await page.route("**/api/account/travel/**", route => {
    if (route.request().url().endsWith("/places")) return route.fulfill({ json: { places: [plan.places[0]], missing: 0 } });
    if (route.request().method() !== "GET") payload = route.request().postDataJSON().payload;
    return route.fulfill({ json: { id, payload, role, revision: 2, updatedAt: Date.now(), members: [], votes: [], comments: [], invitationActive: false } });
  });
  await page.goto(`/my-trips/${id}`);
  const choice = page.getByRole("combobox", { name: "경남도립미술관 머무는 시간", exact: true });
  await expect(waveSelectNative(choice)).toHaveValue("saved");
  await chooseWaveOption(choice, "60");
  expect(payload.visitMinutesByPlaceId["1001"]).toBe(45);
  await page.getByRole("button", { name: "변경 사항 저장", exact: true }).click();
  await expect(page.getByText("여행 변경 사항을 계정에 저장했어요.")).toBeVisible();
  expect(payload.visitMinutesByPlaceId["1001"]).toBe(60);
  role = "member";
  await page.reload();
  await expect(page.getByText("체류 60분", { exact: true })).toBeVisible();
  await expect(choice).toHaveCount(0);
});

test('고정 방문·체류·휴식은 실제 시간표와 저장에 반영하고 이동 기준 도착은 유지한다', async ({ page }) => {
  await page.route('**/api/**', route => route.fulfill({ status: 503, json: { error: 'Unconfigured synthetic API' } }));
  await mockPublicShellApi(page);
  await mockPlannerApi(page, { preserveView: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/planner');
  await chooseTripConditions(page);
  for (const name of ['경남도립미술관', '용지호수공원']) await page.getByRole('button', { name: `${name} 일정에 담기`, exact: true }).click();
  await openItinerary(page, { start: '2026-10-08' });
  await page.getByRole('button', { name: '여행 설정', exact: true }).click();
  const settings = page.getByRole('dialog', { name: '여행 설정', exact: true });
  await settings.getByLabel('하루 시작', { exact: true }).fill('10:00');
  await chooseWaveOption(settings.getByRole('combobox', { name: '이동 수단', exact: true }), 'car');
  await settings.getByRole('button', { name: '적용', exact: true }).click();
  const arrivals = page.locator('.simple-stops .simple-stop > time');
  await expect(arrivals).toHaveText(['10:25 도착 예정', '10:50 도착 예정']);
  const visits = page.locator('.simple-timing-mode details');
  await visits.getByText('방문 시간표', { exact: true }).click();
  const previousVisits = await visits.locator('li').allTextContents();
  await page.getByRole('button', { name: '경남도립미술관 일정 수정', exact: true }).click();
  const editor = page.getByRole('dialog', { name: '경남도립미술관 수정', exact: true });
  await chooseWaveOption(editor.getByRole('combobox', { name: '경남도립미술관 머무는 시간', exact: true }), '60');
  await editor.getByText('휴식·고정 방문', { exact: true }).click();
  await chooseWaveOption(editor.getByRole('combobox', { name: '경남도립미술관 방문 뒤 휴식', exact: true }), '15');
  await chooseWaveOption(editor.getByRole('combobox', { name: '경남도립미술관 장소 고정', exact: true }), 'visit');
  await editor.getByLabel('경남도립미술관 고정 도착 시각', { exact: true }).fill('11:00');
  expect(await visits.locator('li').allTextContents()).toEqual(previousVisits);
  await editor.getByRole('button', { name: '적용', exact: true }).click();
  await expect(visits.locator('li').filter({ hasText: '경남도립미술관' })).toContainText('11:00–12:15 · 관람 60분 · 휴식 15분');
  await expect(visits.locator('li').filter({ hasText: '용지호수공원' })).toContainText('12:40');
  await expect(arrivals).toHaveText(['10:25 도착 예정', '10:50 도착 예정']);
  await page.getByRole('button', { name: '내 여행에 저장', exact: true }).click();
  await acceptTripTimingWarning(page);
  await expect(page.locator('.simple-save-control [role=status]')).toContainText('내 여행에 저장했어요');
  await page.goto('/travel-book');
  await page.getByRole('button', { name: '일정 열기', exact: true }).click();
  await visits.getByText('방문 시간표', { exact: true }).click();
  await expect(visits.locator('li').filter({ hasText: '경남도립미술관' })).toContainText('11:00–12:15 · 관람 60분 · 휴식 15분');
  await expect(arrivals).toHaveText(['10:25 도착 예정', '10:50 도착 예정']);
  await page.getByRole('button', { name: '경남도립미술관 일정 수정', exact: true }).click();
  await editor.getByText('휴식·고정 방문', { exact: true }).click();
  await expect(waveSelectNative(editor.getByRole('combobox', { name: '경남도립미술관 장소 고정', exact: true }))).toHaveValue('visit');
  await expect(editor.getByLabel('경남도립미술관 고정 도착 시각', { exact: true })).toHaveValue('11:00');
  await expect(editor.getByRole('button', { name: '일정에서 빼기', exact: true })).toBeDisabled();
  await expect(waveSelectNative(editor.getByRole('combobox', { name: '방문 날짜', exact: true }))).toBeDisabled();
  await chooseWaveOption(editor.getByRole('combobox', { name: '경남도립미술관 장소 고정', exact: true }), '');
  await editor.getByRole('button', { name: '적용', exact: true }).click();
  await expect(visits.locator('li').filter({ hasText: '경남도립미술관' })).toContainText('10:25–11:40 · 관람 60분 · 휴식 15분');
  await expect(visits.locator('li').filter({ hasText: '용지호수공원' })).toContainText('12:05');
  await expect(arrivals).toHaveText(['10:25 도착 예정', '10:50 도착 예정']);
});
