import {test,expect,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mockPublicShellApi,mockPlannerApi,chooseTripConditions} from './fixtures';
import {alternativePlan} from './alternative-fixtures';
async function setup(page:Page,auto=false){
 await mockPublicShellApi(page);await mockPlannerApi(page,{preserveView:true});await page.emulateMedia({reducedMotion:'reduce'});await page.route('**/api/wave?action=plan*',route=>route.fulfill({json:alternativePlan}));
 await page.addInitScript((auto)=>{if(localStorage.getItem('wave-trip-order-v1'))return;localStorage.setItem('wave-trip-order-v1',JSON.stringify({mode:auto?'auto':'manual',ids:auto?['1002','1001']:['1001','1002']}));localStorage.setItem('wave-trip-schedule-v1',JSON.stringify({travelStart:'2026-10-08',travelEnd:'2026-10-09',dayStartTime:'10:00',scheduleAssignments:{1001:'2026-10-08',1002:'2026-10-08'},visitMinutesByPlaceId:{1002:45},breakMinutesByPlaceId:{1002:15},restPurposeByPlaceId:{1002:'rest'}}));},auto);
 await page.goto('/planner');await chooseTripConditions(page);for(const name of ['경남도립미술관','용지호수공원'])await page.getByRole('button',{name:name+' 일정에 추가',exact:true}).click();await page.locator('.reference-journey-views button').nth(1).click();await page.getByText('말로 일정 다루기',{exact:true}).click();
}
const tool=(page:Page)=>page.getByRole('region',{name:'음성과 글로 일정 조작',exact:true});
const snapshot=(page:Page)=>page.evaluate(()=>({ids:localStorage.getItem('wave-saved-places'),schedule:localStorage.getItem('wave-trip-schedule-v1'),order:localStorage.getItem('wave-trip-order-v1')}));
async function command(page:Page,text:string){await tool(page).getByLabel('말하거나 입력할 명령',{exact:true}).fill(text);await tool(page).getByRole('button',{name:'명령 확인',exact:true}).click();}
test('typed confirmed add/remove and undo keep one place’s original date, order, duration and rest',async({page},info)=>{
 await setup(page);const panel=tool(page),before=await page.evaluate(()=>({ids:localStorage.getItem('wave-saved-places'),schedule:localStorage.getItem('wave-trip-schedule-v1'),order:localStorage.getItem('wave-trip-order-v1')}));
 await command(page,'시민문화쉼터 담아줘');await expect(panel.getByRole('heading',{name:'이 작업을 할까요?',exact:true})).toBeFocused();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('wave-saved-places')||'[]').length)).toBe(2);await panel.getByRole('button',{name:'이 작업 취소',exact:true}).click();await expect(panel.getByLabel('말하거나 입력할 명령',{exact:true})).toBeFocused();
 await command(page,'시민문화쉼터 담아줘');await panel.getByRole('button',{name:'확인하고 실행',exact:true}).click();await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(3);await panel.getByRole('button',{name:'방금 음성·문자 작업 되돌리기',exact:true}).click();await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(2);
 await command(page,'용지호수공원 빼줘');await panel.getByRole('button',{name:'확인하고 실행',exact:true}).click();await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(1);await panel.getByRole('button',{name:'방금 음성·문자 작업 되돌리기',exact:true}).click();await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(2);
 expect(await page.evaluate(()=>({ids:localStorage.getItem('wave-saved-places'),schedule:localStorage.getItem('wave-trip-schedule-v1'),order:localStorage.getItem('wave-trip-order-v1')}))).toEqual(before);
 for(const width of info.project.name.includes('desktop')?[1440,960]:[390,320]){await page.setViewportSize({width,height:960});await panel.scrollIntoViewIfNeeded();await page.evaluate(()=>scrollBy(0,-150));await page.screenshot({path:info.outputPath(`voice-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBe(0);expect((await new AxeBuilder({page}).include('[aria-label="음성과 글로 일정 조작"]').analyze()).violations).toEqual([]);}
});
type VoiceDouble={start:()=>void;abort:()=>void;onresult:((event:{resultIndex:number;results:Array<{isFinal:boolean;0:{transcript:string}}>})=>void)|null;onerror:((event:{error:string})=>void)|null;lang?:string;continuous?:boolean;interimResults?:boolean};
type VoiceWindow={SpeechRecognition?:new()=>VoiceDouble;webkitSpeechRecognition?:new()=>VoiceDouble;voiceDoubles:VoiceDouble[];voiceStarts:number;voiceAborts:number;lateVoiceResult?:VoiceDouble['onresult']};
test('microphone is opt-in, a synthetic final result needs confirmation, cancel/denied/unsupported fall back to typing',async({page})=>{
 await page.addInitScript(()=>{const target=window as unknown as VoiceWindow;target.voiceDoubles=[];target.voiceStarts=0;target.voiceAborts=0;target.SpeechRecognition=class{onresult:VoiceDouble['onresult']=null;onerror:VoiceDouble['onerror']=null;constructor(){target.voiceDoubles.push(this);}start(){target.voiceStarts++;}stop(){}abort(){target.voiceAborts++;}};target.webkitSpeechRecognition=undefined;});
 await setup(page);const panel=tool(page);expect(await page.evaluate(()=>(window as unknown as VoiceWindow).voiceStarts)).toBe(0);await panel.getByRole('button',{name:'마이크로 말하기',exact:true}).click();expect(await page.evaluate(()=>{const test=window as unknown as VoiceWindow;return{starts:test.voiceStarts,lang:test.voiceDoubles[0].lang,continuous:test.voiceDoubles[0].continuous};})).toEqual({starts:1,lang:'ko-KR',continuous:false});
 await page.evaluate(()=>{(window as unknown as VoiceWindow).voiceDoubles[0].onresult?.({resultIndex:0,results:[{isFinal:true,0:{transcript:'시민문화쉼터 담아줘'}}]});});await expect(panel.getByRole('heading',{name:'이 작업을 할까요?',exact:true})).toBeVisible();await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(2);await panel.getByRole('button',{name:'이 작업 취소',exact:true}).click();
 await panel.getByRole('button',{name:'마이크로 말하기',exact:true}).click();await page.evaluate(()=>{const target=window as unknown as VoiceWindow;target.lateVoiceResult=target.voiceDoubles.at(-1)?.onresult;});await panel.getByRole('button',{name:'듣기 취소',exact:true}).click();await page.evaluate(()=>{(window as unknown as VoiceWindow).lateVoiceResult?.({resultIndex:0,results:[{isFinal:true,0:{transcript:'용지호수공원 빼줘'}}]});});await expect(panel.getByRole('region',{name:'음성 명령 미리보기'})).toHaveCount(0);
 await panel.getByRole('button',{name:'마이크로 말하기',exact:true}).click();await page.evaluate(()=>{const target=window as unknown as VoiceWindow;target.lateVoiceResult=target.voiceDoubles.at(-1)?.onresult;});const aborts=await page.evaluate(()=>(window as unknown as VoiceWindow).voiceAborts);await page.getByRole('button',{name:'다음: 전체보기',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as unknown as VoiceWindow).voiceAborts)).toBe(aborts+1);await page.evaluate(()=>{(window as unknown as VoiceWindow).lateVoiceResult?.({resultIndex:0,results:[{isFinal:true,0:{transcript:'용지호수공원 빼줘'}}]});});expect(await page.locator('[aria-label="음성 명령 미리보기"]').count()).toBe(0);await page.locator('.reference-journey-views button').nth(1).click();await expect(panel).toBeVisible();await expect(panel.getByRole('button',{name:'마이크로 말하기',exact:true})).toBeVisible();
 await command(page,'시민문화쉼터 담아줘');await page.getByRole('button',{name:'다음: 전체보기',exact:true}).click();await page.locator('.reference-journey-views button').nth(1).click();await expect(panel.getByRole('region',{name:'음성 명령 미리보기'})).toHaveCount(0);
 await panel.getByRole('button',{name:'마이크로 말하기',exact:true}).click();await page.evaluate(()=>{(window as unknown as VoiceWindow).voiceDoubles.at(-1)?.onerror?.({error:'not-allowed'});});await expect(panel).toContainText('허용되지 않았어요');await expect(panel.getByLabel('말하거나 입력할 명령',{exact:true})).toBeEnabled();
 await page.evaluate(()=>{const target=window as unknown as VoiceWindow;target.SpeechRecognition=undefined;target.webkitSpeechRecognition=undefined;});await panel.getByRole('button',{name:'마이크로 말하기',exact:true}).click();await expect(panel).toContainText('지원하지 않아요');await command(page,'모두 삭제하고 친구에게 보내줘');await expect(panel.getByRole('region',{name:'음성 명령 미리보기'})).toHaveCount(0);await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(2);
});
test('a changed date invalidates preview and a new edit protects the newer choice from undo',async({page})=>{
 await setup(page);const panel=tool(page);await command(page,'시민문화쉼터 담아줘');await panel.getByRole('combobox',{name:'조작할 여행 날짜',exact:true}).selectOption('2026-10-09');await expect(panel.getByRole('button',{name:'확인하고 실행',exact:true})).toBeDisabled();await expect(panel).toContainText('여행 조건이나 일정이 바뀌었어요');await command(page,'시민문화쉼터 담아줘');await panel.getByRole('button',{name:'확인하고 실행',exact:true}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('wave-trip-schedule-v1')||'{}').scheduleAssignments['1003'])).toBe('2026-10-09');
 await panel.getByRole('combobox',{name:'조작할 여행 날짜',exact:true}).selectOption('2026-10-08');await panel.getByRole('button',{name:'방금 음성·문자 작업 되돌리기',exact:true}).click();await expect(panel).toContainText('자동으로 되돌리지 않았습니다');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('wave-saved-places')||'[]').includes('1003'))).toBe(true);
 await command(page,'다음 장소 보여줘');await panel.getByRole('button',{name:'확인하고 실행',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(panel.getByLabel('말하거나 입력할 명령',{exact:true})).toBeFocused();
});

test('undo restores a removed first place and the inactive manual order while automatic order was selected',async({page})=>{
 await setup(page,true);const panel=tool(page),before=await snapshot(page);expect(JSON.parse(before.order||'{}')).toEqual({mode:'auto',ids:['1002','1001']});
 await command(page,'경남도립미술관 빼줘');await panel.getByRole('button',{name:'확인하고 실행',exact:true}).click();await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(1);await panel.getByRole('button',{name:'방금 음성·문자 작업 되돌리기',exact:true}).click();await expect.poll(()=>snapshot(page)).toEqual(before);
 await command(page,'시민문화쉼터 담아줘');await panel.getByRole('button',{name:'확인하고 실행',exact:true}).click();await expect(page.locator('.reference-day-list .reference-stop')).toHaveCount(3);await panel.getByRole('button',{name:'방금 음성·문자 작업 되돌리기',exact:true}).click();await expect.poll(()=>snapshot(page)).toEqual(before);
});
