import { communitySearchPattern } from "../../../lib/community/validation.js";
import { communityDatabase, type CommunityRow } from "./database";
import { mapCommunityComment, mapCommunityPost } from "./post-mappers";
import type { ListFilters } from "./types";

export async function listCommunityPosts(filters: ListFilters, userId: string, options: { fieldReportEnabled?: boolean } = {}) {
  const sql = await communityDatabase();
  if (!sql) return null;
  const { category, search, placeId, page, limit, offset } = filters;
  const pattern = communitySearchPattern(search);
  const take = limit + 1;
  const fieldReportsVisible = options.fieldReportEnabled === true;
  const journalPlace = JSON.stringify([{ id: placeId }]);
  if (filters.placePreview && placeId) {
    // Partition before limiting: recent reports must not crowd out visitor stories.
    // The same server flag as every public list applies inside the query.
    const previewRows = await sql`WITH ranked AS (
      SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, ROW_NUMBER() OVER (PARTITION BY (p.category='field-report') ORDER BY p.created_at DESC,p.id DESC) AS preview_rank,
        (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count,
        (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count,
        EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me
      FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report')
        AND p.author_id <> 'wave-seed'
        AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul','YYYY-MM-DD'))
        AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul','YYYY-MM-DD'))
        AND (p.place_id=${placeId} OR p.journal_places @> ${journalPlace}::jsonb)
    ) SELECT * FROM ranked WHERE preview_rank <= ${Math.min(limit, 3)} ORDER BY created_at DESC,id DESC` as CommunityRow[];
    return { posts: previewRows.filter(row => row.category !== 'field-report').map(row => mapCommunityPost(row,userId)),
      fieldReports: previewRows.filter(row => row.category === 'field-report').map(row => mapCommunityPost(row,userId)), page: 1, hasMore: false };
  }
  const rows = filters.history && placeId
    ? await sql`SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND p.place_id=${placeId} AND p.category='review' AND p.visit_date IS NOT NULL AND jsonb_array_length(p.field_reports)>0 ORDER BY p.visit_date DESC, p.created_at DESC LIMIT ${take} OFFSET ${offset}`
    : placeId && category
    ? await sql`SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND p.place_id=${placeId} AND p.category=${category} ORDER BY CASE WHEN ${filters.sort === 'popular'} THEN (SELECT COUNT(*) FROM community_likes sort_likes WHERE sort_likes.post_id=p.id) ELSE 0 END DESC, CASE WHEN ${filters.sort === 'comments'} THEN (SELECT COUNT(*) FROM community_comments sort_comments WHERE sort_comments.post_id=p.id AND sort_comments.moderation_status='active') ELSE 0 END DESC, p.created_at DESC, p.id DESC LIMIT ${take} OFFSET ${offset}`
    : placeId
    ? await sql`SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND (p.place_id=${placeId} OR p.journal_places @> ${journalPlace}::jsonb) ORDER BY CASE WHEN ${filters.sort === 'popular'} THEN (SELECT COUNT(*) FROM community_likes sort_likes WHERE sort_likes.post_id=p.id) ELSE 0 END DESC, CASE WHEN ${filters.sort === 'comments'} THEN (SELECT COUNT(*) FROM community_comments sort_comments WHERE sort_comments.post_id=p.id AND sort_comments.moderation_status='active') ELSE 0 END DESC, p.created_at DESC, p.id DESC LIMIT ${take} OFFSET ${offset}`
    : category && search
      ? await sql`SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND p.category=${category} AND (p.title ILIKE ${pattern} OR p.content ILIKE ${pattern} OR COALESCE(p.place_name,'') ILIKE ${pattern} OR p.journal_places::text ILIKE ${pattern}) ORDER BY CASE WHEN ${filters.sort === 'popular'} THEN (SELECT COUNT(*) FROM community_likes sort_likes WHERE sort_likes.post_id=p.id) ELSE 0 END DESC, CASE WHEN ${filters.sort === 'comments'} THEN (SELECT COUNT(*) FROM community_comments sort_comments WHERE sort_comments.post_id=p.id AND sort_comments.moderation_status='active') ELSE 0 END DESC, p.created_at DESC, p.id DESC LIMIT ${take} OFFSET ${offset}`
      : category
        ? await sql`SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND p.category=${category} ORDER BY CASE WHEN ${filters.sort === 'popular'} THEN (SELECT COUNT(*) FROM community_likes sort_likes WHERE sort_likes.post_id=p.id) ELSE 0 END DESC, CASE WHEN ${filters.sort === 'comments'} THEN (SELECT COUNT(*) FROM community_comments sort_comments WHERE sort_comments.post_id=p.id AND sort_comments.moderation_status='active') ELSE 0 END DESC, p.created_at DESC, p.id DESC LIMIT ${take} OFFSET ${offset}`
        : search
          ? await sql`SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND (p.title ILIKE ${pattern} OR p.content ILIKE ${pattern} OR COALESCE(p.place_name,'') ILIKE ${pattern} OR p.journal_places::text ILIKE ${pattern}) ORDER BY CASE WHEN ${filters.sort === 'popular'} THEN (SELECT COUNT(*) FROM community_likes sort_likes WHERE sort_likes.post_id=p.id) ELSE 0 END DESC, CASE WHEN ${filters.sort === 'comments'} THEN (SELECT COUNT(*) FROM community_comments sort_comments WHERE sort_comments.post_id=p.id AND sort_comments.moderation_status='active') ELSE 0 END DESC, p.created_at DESC, p.id DESC LIMIT ${take} OFFSET ${offset}`
          : await sql`SELECT p.id,p.author_id,p.author_name,p.category,p.title,p.content,p.region,p.place_id,p.place_name,p.visit_date,p.field_reports,p.journal_places,p.created_at,p.updated_at,jsonb_array_length(p.visit_photos) photo_count, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) ORDER BY CASE WHEN ${filters.sort === 'popular'} THEN (SELECT COUNT(*) FROM community_likes sort_likes WHERE sort_likes.post_id=p.id) ELSE 0 END DESC, CASE WHEN ${filters.sort === 'comments'} THEN (SELECT COUNT(*) FROM community_comments sort_comments WHERE sort_comments.post_id=p.id AND sort_comments.moderation_status='active') ELSE 0 END DESC, p.created_at DESC, p.id DESC LIMIT ${take} OFFSET ${offset}`;
  const typedRows = rows as CommunityRow[];
  return { posts: typedRows.slice(0, limit).map((row) => mapCommunityPost(row, userId)), page, hasMore: typedRows.length > limit };
}
export async function getCommunityPost(postId: string, userId: string, options: { fieldReportEnabled?: boolean } = {}) {
  const sql = await communityDatabase();
  if (!sql) return null;
  const fieldReportsVisible = options.fieldReportEnabled === true;
  const rows = await sql`SELECT p.*, (SELECT COUNT(*) FROM community_comments c WHERE c.post_id=p.id AND c.moderation_status='active') comment_count, (SELECT COUNT(*) FROM community_likes l WHERE l.post_id=p.id) like_count, EXISTS(SELECT 1 FROM community_likes l WHERE l.post_id=p.id AND l.user_id=${userId}) liked_by_me FROM community_posts p WHERE p.id=${postId} AND p.moderation_status='active' AND (${fieldReportsVisible} OR p.category <> 'field-report') AND p.author_id <> 'wave-seed' AND (p.visit_date IS NULL OR p.visit_date <= to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p.journal_places) item WHERE item->>'day' > to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD')) LIMIT 1` as CommunityRow[];
  if (!rows[0]) return { missing: true as const };
  const comments = await sql`SELECT * FROM community_comments WHERE post_id=${postId} AND moderation_status='active' ORDER BY created_at ASC` as CommunityRow[];
  return { post: mapCommunityPost(rows[0], userId), comments: comments.map((row) => mapCommunityComment(row, userId)) };
}
