import Link from "next/link";
import TravelShell from "../../features/account-travel/TravelShell";
import { pageMetadata } from "../../lib/site-metadata";
export const metadata = pageMetadata({ title: "W.A.V.E 사용 방법", description: "여행 저장, 여러 기기에서 이어하기, 편의 조건과 동행자 초대 사용 방법을 알아보세요.", path: "/guide" });
export default function Page() {
  return <TravelShell title="여행을 잇는 방법">
    <nav className="travel-book-actions" aria-label="사용 방법 목차"><a href="#account-travel-guide">내 여행 저장</a><a href="#preferences">편의 조건</a><a href="#companions">동행자</a><a href="#kakao-share">카카오톡 공유</a><a href="#kakao-self">나에게 보내기</a><a href="#taxi">택시로 이동</a></nav>
    <section className="account-settings" id="account-travel-guide"><h2>01. 내 여행을 여러 기기에서 이어가기</h2><ol><li><Link href="/planner">여행 계획</Link>에서 지역·편의·활동·날짜를 고르고 장소를 일정에 담습니다.</li><li>일정의 <b>계정에 저장</b>을 누릅니다. 로그인 전에는 먼저 내 일정에 저장해 두고 로그인할 수 있습니다.</li><li><Link href="/my-trips">계정에 저장한 여행</Link>에서 여행을 열어 날짜·순서·메모를 바꾼 뒤 <b>변경 사항 저장</b>을 누릅니다.</li><li>다른 기기에서도 같은 카카오 또는 W.A.V.E 계정으로 로그인하면 저장한 여행이 보입니다.</li></ol><p>이미 보관한 일정은 <Link href="/travel-book">내 일정</Link>에서 골라 계정에 저장하세요. 기존 여행이 로그인만으로 자동 업로드되지는 않습니다.</p><p>다른 화면에서 동시에 편집하면 최신 버전을 확인하거나 내 수정본을 새 여행으로 보관할 수 있습니다. 오프라인에서 바꾼 내용은 연결이 돌아온 뒤 저장해 주세요. 저장 완료 안내 전에는 화면을 닫지 마세요.</p><p>계정에는 여행 20개, 여행당 장소 12곳·최대 7일을 보관합니다. 장소 이름과 주소는 <b>장소 이름·최신 정보 확인</b>으로 다시 확인할 수 있습니다.</p></section>
    <section className="account-settings" id="preferences"><h2>02. 내가 고른 편의 조건 기억하기</h2><ol><li>여행 계획의 <b>편의 조건 저장·불러오기</b>를 펼칩니다.</li><li>현재 조건을 확인하고 <b>편의 조건을 계정에 저장</b>을 누릅니다.</li><li>다음 여행이나 다른 기기에서 <b>계정 편의 불러오기</b>를 누르면 선택이 적용됩니다.</li></ol><p>선택한 편의 조건만 저장하며 동행자에게 공유하지 않습니다. 저장을 원하지 않으면 이용하지 않아도 되고, <b>계정 편의 삭제</b>로 지울 수 있어요.</p></section>
    <section className="account-settings" id="companions"><h2>03. 동행자와 함께 계획하기</h2><ol><li>계정 여행을 열고 <b>초대 링크 만들기</b>를 누릅니다.</li><li>복사한 링크를 원하는 동행자에게 전달합니다. 초대는 7일 동안 유효합니다.</li><li>동행자는 로그인하고 표시 이름을 입력한 뒤 <b>여행에 참여하기</b>를 누릅니다.</li><li>장소의 <b>가고 싶어요</b>로 투표하고 <b>의견 남기기</b>로 준비할 내용을 나눕니다. 여행을 만든 사람이 의견을 보고 최종 일정을 수정합니다.</li></ol><p>한 여행에 만든 사람 포함 최대 10명이 참여할 수 있습니다. <b>초대 중지</b>는 새 참여를 막고, 참여 해제는 해당 동행자의 접근·투표·의견을 삭제합니다. 링크는 함께할 사람에게만 전달해 주세요.</p></section>
    <section className="account-settings" id="kakao-share"><h2>04. 카카오톡으로 여행 카드 공유하기</h2><ol><li>여행 일정 또는 <Link href="/travel-book">내 일정</Link>, <Link href="/my-trips">계정 여행</Link>에서 <b>카카오톡 여행 카드 만들기</b>를 누릅니다.</li><li>지역·날짜·장소 수를 확인하고 <b>카카오톡으로 공유</b>를 누릅니다.</li><li>카카오톡에서 보낼 친구나 대화방을 직접 선택합니다.</li></ol><p>받은 사람은 30일 동안 공개 여행 링크로 일정을 볼 수 있습니다. 편의 조건, 메모, 현재 위치와 동행자 의견은 공개 카드에 넣지 않습니다. 친구 목록을 W.A.V.E에 제공할 필요도 없습니다. 카카오톡을 사용할 수 없으면 <b>여행 링크 복사</b>를 이용하세요.</p></section>
    <section className="account-settings" id="kakao-self"><h2>05. 내 카카오톡에 여행 챙겨두기</h2><ol><li>여행을 <b>계정에 저장</b>한 뒤 여행을 엽니다.</li><li><b>카카오톡 나에게 보내기</b>를 누릅니다. 처음에는 <b>카카오 메시지 전송 동의하기</b>로 카카오에서 동의를 진행합니다.</li><li>여행 화면으로 돌아와 보내기 버튼을 다시 누릅니다.</li><li>카카오톡 <b>나와의 채팅</b>에서 날짜·장소 수를 확인하고 <b>내 여행 이어가기</b>를 누릅니다.</li></ol><p>메시지는 요청한 때만 보냅니다. 내 여행 링크는 로그인과 여행 참여 권한이 있어야 열립니다. 저장하지 않은 수정본은 먼저 저장해 주세요. 메시지 동의를 거절해도 여행 기능을 사용할 수 있습니다. 같은 여행은 중복을 막기 위해 1분에 한 번 보낼 수 있습니다.</p></section>
    <section className="account-settings" id="taxi"><h2>06. 카카오 T에서 택시로 이어가기</h2><ol><li>지도에서 목적지를 선택하거나 계정 여행에서 장소 이름을 확인합니다.</li><li><b>목적지 복사</b>를 누르고 <b>카카오 T 열기</b>로 이동합니다.</li><li>카카오 T에서 목적지를 검색하고 실제 출발지·차량·요금을 확인한 뒤 호출합니다.</li></ol><p>W.A.V.E 버튼은 카카오 T 실행 화면으로 연결됩니다. 택시 배차나 결제가 W.A.V.E에서 자동으로 실행되지는 않습니다. 휠체어 탑승 등 필요한 차량 조건은 호출 전 확인하세요.</p></section>
  </TravelShell>;
}
