import type { Locale } from "./types";

export const localeOptions: Array<{ id: Locale; label: string; short: string; beta: boolean }> = [
  { id: "ko", label: "한국어", short: "KO", beta: false },
  { id: "en", label: "English", short: "EN", beta: true },
  { id: "ja", label: "日本語", short: "JA", beta: true },
  { id: "zh-Hans", label: "简体中文", short: "简", beta: true },
  { id: "zh-Hant", label: "繁體中文", short: "繁", beta: true },
  { id: "fr", label: "Français", short: "FR", beta: true },
  { id: "de", label: "Deutsch", short: "DE", beta: true },
  { id: "ru", label: "Русский", short: "RU", beta: true },
];

export const motionCopy: Record<Locale, { on: string; off: string }> = {
  ko: { on: "파동 효과 켜기", off: "파동 효과 끄기" },
  en: { on: "Turn wave effects on", off: "Turn wave effects off" },
  ja: { on: "波の効果をオン", off: "波の効果をオフ" },
  "zh-Hans": { on: "开启波浪效果", off: "关闭波浪效果" },
  "zh-Hant": { on: "開啟波浪效果", off: "關閉波浪效果" },
  fr: { on: "Activer les vagues", off: "Désactiver les vagues" },
  de: { on: "Welleneffekt einschalten", off: "Welleneffekt ausschalten" },
  ru: { on: "Включить эффект волн", off: "Выключить эффект волн" },
};

export const copy: Record<Locale, Record<string, string>> = {
  ko: {},
  en: {
    skip: "Skip to content", service: "Service", regions: "18 regions", data: "Data", use: "Use service",
    heroBadge: "Accessible travel in Gyeongsangnam-do", heroTitle: "Beyond places you can reach,", heroEm: "toward a day you want.",
    heroCopy: "W.A.V.E connects each traveler’s mobility needs with regional tourism data, from choosing a place to planning the actual journey.", plan: "Plan my trip", learn: "Learn about W.A.V.E",
    tourism: "Tourism", accessible: "Accessibility", mobility: "Mobility", stories: "Local stories",
    whyTitle: "There is plenty of travel information, but it is still hard to know whether I can go.",
    value1: "Needs first", value1Copy: "Start with real needs such as wheelchair use, reduced walking, infants, pregnancy, and visual or hearing support.",
    value2: "Evidence included", value2Copy: "See access routes, restrooms, elevators, data dates and confidence—not photos alone.",
    value3: "Connect the journey", value3Copy: "Compare time, fare, transfers and walking to design the whole day.",
    regionTitle: "Eighteen stories live inside the boundary of Gyeongsangnam-do.", regionCopy: "Select a marker to see its story and start planning for that region.", selected: "Selected region", makeTrip: "Plan a trip",
    evidenceTitle: "See the reason for each recommendation—and its limits.", evidence1: "Places and photos", evidence1Copy: "Cross-check official tourism and photo data by region and place.", evidence2: "Accessibility and mobility", evidence2Copy: "Compare facility access, walking, transfers, time and estimated fare separately.", evidence3: "Update time", evidence3Copy: "Separate official certification from W.A.V.E fit and show freshness and confidence.",
    ctaTitle: "The introduction ends here.", ctaEm: "Now plan the actual trip.", start: "Start W.A.V.E", footer: "An accessible Gyeongsangnam-do travel guide for everyone",
    conditions: "Trip setup", route: "Directions", evidence: "Evidence", saved: "Saved trips", studioTitle: "From your needs to the journey,", studioEm: "build the real trip here.", studioCopy: "Compare attractions, photos, accessibility, crowd levels and mobility in one place.",
    startFrom: "Where are you starting?", destination: "Where are you going?", enjoy: "What do you enjoy?", support: "What support do you need?", currentLocation: "Current location", search: "Build a course with public data", selectedCount: "selected",
    placesTitle: "Check comfort before you move.", layersTitle: "See one region in seven different ways.", navigationTitle: "Compare how to get there—not only where to go.", routeTitle: "Your accessible day", dataTitle: "We do not hide the evidence.",
    language: "Language", dark: "Dark mode", light: "Light mode",
  },
  ja: {
    skip: "本文へ移動", service: "サービス", regions: "慶南18地域", data: "データ", use: "サービスを利用",
    heroBadge: "慶尚南道バリアフリー旅行", heroTitle: "行ける場所を越えて、", heroEm: "行きたい一日へ。", heroCopy: "W.A.V.Eは旅行者の移動条件と慶南の観光データを結び、場所選びから実際の移動まで設計します。", plan: "旅行を設計", learn: "サービス紹介",
    tourism: "観光情報", accessible: "バリアフリー", mobility: "移動経路", stories: "地域の物語", whyTitle: "旅行情報は多くても、自分が行けるかどうかは分かりにくいものです。",
    value1: "条件を先に", value1Copy: "車いす、歩行負担、乳幼児、妊婦、視聴覚支援など実際の条件から始めます。", value2: "根拠も一緒に", value2Copy: "アクセス路・トイレ・エレベーター・基準日・信頼度を表示します。", value3: "移動まで接続", value3Copy: "時間・料金・乗換・徒歩を比較して一日を設計します。",
    regionTitle: "慶南の境界には18の物語があります。", regionCopy: "地域マーカーを選び、その地域の旅行設計を始めてください。", selected: "選択地域", makeTrip: "旅行を作る",
    evidenceTitle: "おすすめの理由と限界まで表示します。", evidence1: "観光地と写真", evidence1Copy: "公的な観光・写真データを地域と場所で照合します。", evidence2: "アクセシビリティと移動", evidence2Copy: "施設情報と徒歩・乗換・時間・料金を比較します。", evidence3: "更新時刻", evidence3Copy: "公式認証と適合度を分け、基準日と信頼度を表示します。", ctaTitle: "紹介はここまで。", ctaEm: "実際の旅行を設計しましょう。", start: "W.A.V.Eを開始", footer: "誰もが望む場所へ、慶南バリアフリー旅行ガイド",
    conditions: "旅行条件", route: "経路検索", evidence: "推薦根拠", saved: "保存旅行", studioTitle: "条件から移動まで、", studioEm: "ここで旅行を作ります。", studioCopy: "観光地・写真・アクセシビリティ・混雑度・移動経路を比較します。", startFrom: "出発地は？", destination: "どこへ行きますか？", enjoy: "何を楽しみますか？", support: "必要な支援は？", currentLocation: "現在地", search: "公共データでコース検索", selectedCount: "件選択", placesTitle: "移動前に快適さを確認。", layersTitle: "一つの地域を7つの方法で。", navigationTitle: "目的地だけでなく行き方も比較。", routeTitle: "あなたのバリアフリーな一日", dataTitle: "推薦根拠を隠しません。", language: "言語", dark: "ダークモード", light: "ライトモード",
  },
  "zh-Hans": {
    skip: "跳至正文", service: "服务", regions: "庆南18地区", data: "数据", use: "使用服务",
    heroBadge: "庆尚南道无障碍旅行", heroTitle: "不止能到达，", heroEm: "更是想去的一天。", heroCopy: "W.A.V.E连接旅行者的出行需求与庆南旅游数据，从景点选择到实际路线一站式规划。", plan: "规划我的旅行", learn: "了解服务", tourism: "旅游信息", accessible: "无障碍信息", mobility: "出行路线", stories: "地区故事", whyTitle: "旅行信息很多，但是否适合自己前往仍然很难判断。",
    value1: "需求优先", value1Copy: "从轮椅、步行负担、婴幼儿、孕妇及视听辅助等实际需求出发。", value2: "展示依据", value2Copy: "同时显示通道、卫生间、电梯、数据日期和可信度。", value3: "连接出行", value3Copy: "比较时间、费用、换乘与步行，规划完整一天。",
    regionTitle: "庆南边界内有十八个故事。", regionCopy: "选择地区标记，查看故事并开始规划。", selected: "当前地区", makeTrip: "规划旅行", evidenceTitle: "推荐理由和局限都会展示。", evidence1: "景点与照片", evidence1Copy: "按地区和地点核对官方旅游与照片数据。", evidence2: "无障碍与出行", evidence2Copy: "分别比较设施、步行、换乘、时间和预计费用。", evidence3: "更新时间", evidence3Copy: "区分官方认证与适配度，并显示数据日期和可信度。", ctaTitle: "介绍到此结束。", ctaEm: "现在开始规划实际旅行。", start: "开始W.A.V.E", footer: "面向所有人的庆南无障碍旅行指南",
    conditions: "旅行条件", route: "路线", evidence: "推荐依据", saved: "已收藏", studioTitle: "从需求到出行，", studioEm: "在这里规划真实旅行。", studioCopy: "一处比较景点、照片、无障碍、拥挤度和路线。", startFrom: "从哪里出发？", destination: "要去哪里？", enjoy: "想体验什么？", support: "需要哪些便利？", currentLocation: "当前位置", search: "用公共数据生成路线", selectedCount: "项已选", placesTitle: "出发前先确认舒适度。", layersTitle: "用七种方式探索一个地区。", navigationTitle: "不只选目的地，也比较如何到达。", routeTitle: "你的无障碍一天", dataTitle: "推荐依据完全透明。", language: "语言", dark: "深色模式", light: "浅色模式",
  },
  "zh-Hant": {
    skip: "跳至正文", service: "服務", regions: "慶南18地區", data: "資料", use: "使用服務",
    heroBadge: "慶尚南道無障礙旅行", heroTitle: "不只抵達，", heroEm: "更是想去的一天。", heroCopy: "W.A.V.E連結旅客需求與慶南觀光資料，從景點選擇到實際路線一站式規劃。", plan: "規劃我的旅行", learn: "了解服務", tourism: "觀光資訊", accessible: "無障礙資訊", mobility: "移動路線", stories: "地區故事", whyTitle: "旅行資訊很多，但是否適合自己前往仍很難判斷。",
    value1: "需求優先", value1Copy: "從輪椅、步行負擔、嬰幼兒、孕婦及視聽輔助等實際需求出發。", value2: "展示依據", value2Copy: "同時顯示通道、洗手間、電梯、資料日期和可信度。", value3: "連結移動", value3Copy: "比較時間、費用、轉乘與步行，規劃完整一天。", regionTitle: "慶南邊界內有十八個故事。", regionCopy: "選擇地區標記，查看故事並開始規劃。", selected: "目前地區", makeTrip: "規劃旅行", evidenceTitle: "推薦理由和限制都會展示。", evidence1: "景點與照片", evidence1Copy: "按地區和地點核對官方觀光與照片資料。", evidence2: "無障礙與移動", evidence2Copy: "分別比較設施、步行、轉乘、時間和預估費用。", evidence3: "更新時間", evidence3Copy: "區分官方認證與適配度，並顯示資料日期和可信度。", ctaTitle: "介紹到此結束。", ctaEm: "現在開始規劃實際旅行。", start: "開始 W.A.V.E", footer: "為所有人設計的慶南無障礙旅行指南",
    conditions: "旅行條件", route: "路線", evidence: "推薦依據", saved: "已收藏", studioTitle: "從需求到移動，", studioEm: "在這裡規劃真實旅行。", studioCopy: "一次比較景點、照片、無障礙、擁擠度和路線。", startFrom: "從哪裡出發？", destination: "要去哪裡？", enjoy: "想體驗什麼？", support: "需要哪些便利？", currentLocation: "目前位置", search: "用公共資料產生路線", selectedCount: "項已選", placesTitle: "出發前先確認舒適度。", layersTitle: "用七種方式探索一個地區。", navigationTitle: "不只選目的地，也比較如何抵達。", routeTitle: "你的無障礙一天", dataTitle: "推薦依據完全透明。", language: "語言", dark: "深色模式", light: "淺色模式",
  },
  fr: {
    skip: "Aller au contenu", service: "Service", regions: "18 territoires", data: "Données", use: "Utiliser le service", heroBadge: "Voyage accessible à Gyeongsangnam-do", heroTitle: "Au-delà des lieux accessibles,", heroEm: "vers la journée qui vous ressemble.", heroCopy: "W.A.V.E relie vos besoins de mobilité aux données touristiques régionales, du choix du lieu au trajet réel.", plan: "Planifier mon voyage", learn: "Découvrir W.A.V.E", tourism: "Tourisme", accessible: "Accessibilité", mobility: "Itinéraire", stories: "Récits locaux", whyTitle: "Les informations abondent, mais il reste difficile de savoir si un lieu est vraiment accessible.", value1: "Vos besoins d’abord", value1Copy: "Fauteuil roulant, marche réduite, enfants, grossesse et aides visuelles ou auditives.", value2: "Des preuves visibles", value2Copy: "Accès, toilettes, ascenseurs, date des données et niveau de confiance.", value3: "Jusqu’au trajet", value3Copy: "Comparez durée, coût, correspondances et marche.", regionTitle: "Dix-huit histoires vivent en Gyeongsangnam-do.", regionCopy: "Choisissez une région pour voir son histoire et commencer votre voyage.", selected: "Région choisie", makeTrip: "Créer le voyage", evidenceTitle: "Les raisons et les limites de chaque recommandation.", evidence1: "Lieux et photos", evidence1Copy: "Croisement des données touristiques et photographiques officielles.", evidence2: "Accessibilité et mobilité", evidence2Copy: "Comparaison des équipements, de la marche, des correspondances, du temps et du coût.", evidence3: "Date de mise à jour", evidence3Copy: "Certification officielle, adéquation W.A.V.E, fraîcheur et confiance sont distinguées.", ctaTitle: "La présentation est terminée.", ctaEm: "Planifiez maintenant le vrai voyage.", start: "Démarrer W.A.V.E", footer: "Guide de voyage accessible en Gyeongsangnam-do", conditions: "Préparer", route: "Itinéraire", evidence: "Justificatifs", saved: "Voyages", studioTitle: "De vos besoins au trajet,", studioEm: "construisez le voyage ici.", studioCopy: "Comparez lieux, photos, accessibilité, affluence et mobilité.", startFrom: "Point de départ ?", destination: "Destination ?", enjoy: "Vos envies ?", support: "Aide nécessaire ?", currentLocation: "Ma position", search: "Créer avec les données publiques", selectedCount: "sélectionné(s)", placesTitle: "Vérifiez le confort avant de partir.", layersTitle: "Une région, sept lectures.", navigationTitle: "Comparez aussi la manière d’y aller.", routeTitle: "Votre journée accessible", dataTitle: "Les preuves restent visibles.", language: "Langue", dark: "Mode sombre", light: "Mode clair",
  },
  de: {
    skip: "Zum Inhalt", service: "Service", regions: "18 Regionen", data: "Daten", use: "Service nutzen", heroBadge: "Barrierefreies Reisen in Gyeongsangnam-do", heroTitle: "Mehr als erreichbare Orte –", heroEm: "ein Tag, der zu Ihnen passt.", heroCopy: "W.A.V.E verbindet Mobilitätsbedürfnisse mit regionalen Tourismusdaten – von der Ortswahl bis zur echten Route.", plan: "Reise planen", learn: "W.A.V.E entdecken", tourism: "Tourismus", accessible: "Barrierefreiheit", mobility: "Anreise", stories: "Regionale Geschichten", whyTitle: "Es gibt viele Reiseinformationen, doch die persönliche Zugänglichkeit bleibt oft unklar.", value1: "Bedarf zuerst", value1Copy: "Rollstuhl, kurze Wege, Kinder, Schwangerschaft sowie Seh- und Hörunterstützung.", value2: "Belege sichtbar", value2Copy: "Zugang, Toiletten, Aufzüge, Datenstand und Konfidenz.", value3: "Anreise verbunden", value3Copy: "Zeit, Kosten, Umstiege und Fußwege vergleichen.", regionTitle: "In Gyeongsangnam-do warten achtzehn Geschichten.", regionCopy: "Region wählen, Geschichte ansehen und Reise planen.", selected: "Gewählte Region", makeTrip: "Reise erstellen", evidenceTitle: "Gründe und Grenzen jeder Empfehlung werden gezeigt.", evidence1: "Orte und Fotos", evidence1Copy: "Offizielle Tourismus- und Fotodaten werden abgeglichen.", evidence2: "Barrierefreiheit und Mobilität", evidence2Copy: "Ausstattung, Fußwege, Umstiege, Zeit und Kosten im Vergleich.", evidence3: "Aktualität", evidence3Copy: "Offizielle Zertifizierung, W.A.V.E-Eignung, Datenstand und Vertrauen getrennt.", ctaTitle: "Die Einführung endet hier.", ctaEm: "Planen Sie jetzt die echte Reise.", start: "W.A.V.E starten", footer: "Barrierefreier Reiseführer für Gyeongsangnam-do", conditions: "Reiseprofil", route: "Route", evidence: "Belege", saved: "Gespeichert", studioTitle: "Von Ihren Bedürfnissen bis zur Anreise –", studioEm: "planen Sie hier die echte Reise.", studioCopy: "Orte, Fotos, Barrierefreiheit, Auslastung und Mobilität vergleichen.", startFrom: "Wo starten Sie?", destination: "Wohin geht es?", enjoy: "Was interessiert Sie?", support: "Welche Unterstützung?", currentLocation: "Mein Standort", search: "Route mit offenen Daten erstellen", selectedCount: "ausgewählt", placesTitle: "Komfort vor der Abfahrt prüfen.", layersTitle: "Eine Region auf sieben Arten.", navigationTitle: "Nicht nur das Ziel, auch die Anreise vergleichen.", routeTitle: "Ihr barrierefreier Tag", dataTitle: "Die Datengrundlage bleibt sichtbar.", language: "Sprache", dark: "Dunkelmodus", light: "Hellmodus",
  },
  ru: {
    skip: "К содержанию", service: "Сервис", regions: "18 регионов", data: "Данные", use: "Открыть сервис",
    heroBadge: "Доступные путешествия по Кёнсан-Намдо", heroTitle: "Не только доступные места —", heroEm: "день, куда хочется отправиться.", heroCopy: "W.A.V.E объединяет потребности путешественника и туристические данные региона — от выбора места до маршрута.", plan: "Спланировать поездку", learn: "О сервисе", tourism: "Туризм", accessible: "Доступность", mobility: "Маршрут", stories: "Истории региона", whyTitle: "Информации много, но понять, подходит ли место именно вам, всё ещё сложно.",
    value1: "Сначала потребности", value1Copy: "Учитываем коляску, нагрузку при ходьбе, детей, беременность, зрительную и слуховую поддержку.", value2: "Показываем основания", value2Copy: "Показываем подъезды, туалеты, лифты, дату данных и уверенность.", value3: "Вместе с маршрутом", value3Copy: "Сравниваем время, цену, пересадки и пеший путь.", regionTitle: "В Кёнсан-Намдо живут восемнадцать историй.", regionCopy: "Выберите регион и начните планирование.", selected: "Выбранный регион", makeTrip: "Создать маршрут", evidenceTitle: "Показываем причины рекомендаций и ограничения.", evidence1: "Места и фотографии", evidence1Copy: "Сверяем официальные туристические и фотоданные.", evidence2: "Доступность и дорога", evidence2Copy: "Сравниваем удобства, пеший путь, пересадки, время и цену.", evidence3: "Время обновления", evidence3Copy: "Разделяем официальную сертификацию и оценку W.A.V.E.", ctaTitle: "Знакомство завершено.", ctaEm: "Теперь спланируйте поездку.", start: "Начать W.A.V.E", footer: "Путеводитель по доступным путешествиям в Кёнсан-Намдо",
    conditions: "Условия", route: "Маршрут", evidence: "Основания", saved: "Сохранено", studioTitle: "От потребностей до дороги —", studioEm: "создайте поездку здесь.", studioCopy: "Сравните места, фото, доступность, загруженность и маршрут.", startFrom: "Откуда вы едете?", destination: "Куда поедем?", enjoy: "Что вам нравится?", support: "Какая поддержка нужна?", currentLocation: "Моё местоположение", search: "Найти маршрут по открытым данным", selectedCount: "выбрано", placesTitle: "Проверьте удобство до поездки.", layersTitle: "Семь способов увидеть один регион.", navigationTitle: "Сравните не только место, но и дорогу.", routeTitle: "Ваш доступный день", dataTitle: "Мы показываем основания рекомендаций.", language: "Язык", dark: "Тёмная тема", light: "Светлая тема",
  },
};


